const deModuleTheory = {
A1:[
{title:"Core Phrases & German Sounds",rules:["German has three genders: der (m), die (f), das (n). Learn the article with every new noun.","Vowels with umlauts change sound: a->ae (like 'air'), o->oe (rounded e), u->ue (rounded u).","ss (Eszett) is always a sharp 's' sound, never a 'z'.","Greetings: Guten Morgen / Guten Tag / Guten Abend depending on time of day."],examples:[{src:"Guten Tag, wie heissen Sie?",tr:"Good day, what is your name?"},{src:"Ich heisse Anna. Freut mich.",tr:"My name is Anna. Nice to meet you."},{src:"Das ist mein Buch.",tr:"That is my book."}],keyPattern:"Subject + Verb (position 2) + Rest: Ich trinke Kaffee."},
{title:"Questions & Everyday Choices",rules:["Question words: wer (who), was (what), wo (where), wann (when), warum (why), wie (how).","Yes/no questions invert: verb comes first - 'Sprechen Sie Deutsch?'","Numbers above 20 are read units-first: einundzwanzig = one-and-twenty (21).","To order politely, use 'Ich haette gern...' or 'Ich moechte...'"],examples:[{src:"Wo wohnst du?",tr:"Where do you live?"},{src:"Was kostet das?",tr:"How much is that?"},{src:"Ich haette gern einen Kaffee.",tr:"I would like a coffee."}],keyPattern:"Question word + Verb + Subject: Wann kommst du?"},
{title:"Articles & Sentence Order",rules:["The conjugated verb takes position 2 in a main clause.","Regular present-tense endings: ich -e, du -st, er/sie/es -t, wir -en, ihr -t, sie/Sie -en.","Accusative changes only the masculine article: der -> den (Ich sehe den Mann).","'kein' negates nouns; 'nicht' negates verbs and adjectives."],examples:[{src:"Ich sehe den Hund.",tr:"I see the dog."},{src:"Wir lernen Deutsch.",tr:"We are learning German."},{src:"Das ist kein Problem.",tr:"That is not a problem."}],keyPattern:"Nominative subject + verb + accusative object: Ich habe einen Bruder."},
{title:"Reading, Listening & Context",rules:["Compound nouns are read right-to-left: Haustuer = Haus + Tuer (house door).","Cognates help reading: Haus/house, Wasser/water, Buch/book.","Listen for the verb in position 2 to find the main action.","Time expressions often start the sentence, pushing the verb to position 2: Heute lerne ich."],examples:[{src:"Heute lese ich ein Buch.",tr:"Today I am reading a book."},{src:"Der Apfel ist rot.",tr:"The apple is red."},{src:"Wir gehen ins Kino.",tr:"We are going to the cinema."}],keyPattern:"Time + Verb + Subject + Rest: Morgen besuche ich Oma."},
{title:"Speaking, Writing & Review",rules:["Connect simple ideas with und (and), aber (but), oder (or) - word order stays normal.","'gern' after a verb shows you like doing something: Ich tanze gern.","Build a self-introduction: name, origin, age, languages.","Capitalize ALL nouns in German, always."],examples:[{src:"Ich komme aus Spanien und lerne Deutsch.",tr:"I come from Spain and am learning German."},{src:"Ich spiele gern Fussball.",tr:"I like playing football."},{src:"Mein Name ist Tom. Ich bin zwanzig.",tr:"My name is Tom. I am twenty."}],keyPattern:"Idea 1 + und/aber/oder + Idea 2: Ich lese und ich schreibe."}
],
A2:[
{title:"Talking About the Past (Perfekt)",rules:["Perfekt = haben/sein (position 2) + past participle (at the end).","Most verbs use haben; verbs of movement/change use sein (gehen, fahren, kommen).","Regular participles: ge- + stem + -t (machen -> gemacht).","Many strong verbs change the stem: essen -> gegessen, gehen -> gegangen."],examples:[{src:"Ich habe einen Film gesehen.",tr:"I watched a film."},{src:"Wir sind nach Berlin gefahren.",tr:"We travelled to Berlin."},{src:"Sie hat Kaffee getrunken.",tr:"She drank coffee."}],keyPattern:"Subject + haben/sein + ... + Participle: Ich habe Deutsch gelernt."},
{title:"Getting Around & Asking Directions",rules:["Directions: geradeaus (straight), links (left), rechts (right), zurueck (back).","'zu' + dative for destinations: zum Bahnhof, zur Post.","Ordinal numbers for streets: die erste/zweite/dritte Strasse.","Prepositions of place take dative: an, auf, in, neben, zwischen."],examples:[{src:"Gehen Sie geradeaus und dann links.",tr:"Go straight ahead and then left."},{src:"Wie komme ich zum Markt?",tr:"How do I get to the market?"},{src:"Die Bank ist neben der Apotheke.",tr:"The bank is next to the pharmacy."}],keyPattern:"Wie komme ich zu + dative? Wie komme ich zur Schule?"},
{title:"Separable Verbs & Modal Verbs",rules:["Separable prefix moves to the end in main clauses: aufstehen -> Ich stehe um 7 auf.","Modal verbs (koennen, muessen, duerfen, wollen, sollen, moegen) push the infinitive to the end.","In subordinate clauses, separable verbs stay together at the end.","'moechte' (would like) is the polite form of wollen."],examples:[{src:"Ich rufe dich morgen an.",tr:"I will call you tomorrow."},{src:"Du musst jetzt gehen.",tr:"You have to go now."},{src:"Wir koennen Deutsch sprechen.",tr:"We can speak German."}],keyPattern:"Subject + Modal + ... + Infinitive: Ich will Pizza essen."},
{title:"Stories, Weather & Context",rules:["Weather uses 'es': Es regnet, es schneit, es ist sonnig.","Imperfekt of sein/haben is common in writing: war, hatte.","Sequencing words: zuerst, dann, danach, schliesslich.","Adjective endings change after der/die/das and ein-words."],examples:[{src:"Gestern war das Wetter schoen.",tr:"Yesterday the weather was nice."},{src:"Zuerst habe ich gefruehstueckt, dann bin ich gegangen.",tr:"First I had breakfast, then I left."},{src:"Es ist kalt und windig.",tr:"It is cold and windy."}],keyPattern:"zuerst... dann... danach... schliesslich..."},
{title:"Emails, Travel & Review",rules:["Informal email: 'Hallo...' / 'Liebe(r)...'; sign off 'Viele Gruesse'.","Formal email: 'Sehr geehrte...'; sign off 'Mit freundlichen Gruessen'.","Polite requests use 'koennten Sie...' or 'wuerden Sie...'","Travel basics: Fahrkarte (ticket), Gleis (platform), umsteigen (to change trains)."],examples:[{src:"Sehr geehrte Frau Klein, ich schreibe wegen...",tr:"Dear Mrs. Klein, I am writing regarding..."},{src:"Einmal nach Koeln, bitte.",tr:"One ticket to Cologne, please."},{src:"Mit freundlichen Gruessen, Maria.",tr:"Kind regards, Maria."}],keyPattern:"Sehr geehrte(r)... + body + Mit freundlichen Gruessen"}
],
B1:[
{title:"Expressing Opinions",rules:["Opinion starters: Meiner Meinung nach, Ich bin der Ansicht, Ich finde, dass...","'dass' sends the verb to the end of the clause.","Agree/disagree: Da stimme ich zu / Da bin ich anderer Meinung.","Use weil to give reasons (verb to the end)."],examples:[{src:"Meiner Meinung nach ist das wichtig.",tr:"In my opinion that is important."},{src:"Ich finde, dass wir mehr ueben sollten.",tr:"I think that we should practise more."},{src:"Ich bin anderer Meinung, weil es zu teuer ist.",tr:"I disagree because it is too expensive."}],keyPattern:"Ich finde, dass + ... + Verb(end): Ich finde, dass er recht hat."},
{title:"Subordinate Clauses",rules:["Subordinating conjunctions (weil, dass, wenn, obwohl, damit) send the verb to the end.","If the subordinate clause comes first, the main clause starts with its verb.","'wenn' = if/whenever; 'als' = when (single past event).","Relative clauses use der/die/das as relative pronouns."],examples:[{src:"Obwohl es regnet, gehen wir spazieren.",tr:"Although it is raining, we are going for a walk."},{src:"Ich bleibe zu Hause, weil ich krank bin.",tr:"I am staying home because I am ill."},{src:"Als ich klein war, wohnte ich in Bonn.",tr:"When I was little, I lived in Bonn."}],keyPattern:"Main clause, weil/dass/wenn + ... + Verb(end)."},
{title:"Work, Media & Reported Ideas",rules:["Workplace vocabulary: die Bewerbung, der Lebenslauf, das Gehalt, die Besprechung.","Reported speech often uses Konjunktiv I: Er sagt, er sei muede.","Passive (werden + participle) is common in formal/media texts.","Connectors of consequence: deshalb, deswegen, daher (verb stays in position 2)."],examples:[{src:"Er sagt, er habe keine Zeit.",tr:"He says he has no time."},{src:"Das Produkt wird in Deutschland hergestellt.",tr:"The product is made in Germany."},{src:"Ich bin krank, deshalb bleibe ich zu Hause.",tr:"I am ill, therefore I am staying home."}],keyPattern:"..., deshalb + Verb + Subject: Es regnet, deshalb bleibe ich hier."},
{title:"Advice, Plans & Problem Solving",rules:["Give advice with sollte (Konjunktiv II of sollen): Du solltest mehr schlafen.","Future with werden + infinitive, or present + time word.","'vorhaben' and 'planen' express intentions.","Polite suggestions: Wir koennten..., Wie waere es mit...?"],examples:[{src:"Du solltest einen Arzt fragen.",tr:"You should ask a doctor."},{src:"Naechstes Jahr werde ich nach Wien ziehen.",tr:"Next year I will move to Vienna."},{src:"Wie waere es mit einem Kaffee?",tr:"How about a coffee?"}],keyPattern:"Du solltest + Infinitive: Du solltest mehr ueben."},
{title:"Essays, Interviews & Review",rules:["Structure: Einleitung (intro), Hauptteil (body), Schluss (conclusion).","Balance arguments with einerseits... andererseits...","Summarize with Zusammenfassend / Abschliessend.","In interviews, describe Staerken (strengths) and Schwaechen (weaknesses)."],examples:[{src:"Einerseits ist es teuer, andererseits sehr nuetzlich.",tr:"On one hand it is expensive, on the other very useful."},{src:"Zusammenfassend laesst sich sagen, dass...",tr:"In summary it can be said that..."},{src:"Meine Staerke ist Teamarbeit.",tr:"My strength is teamwork."}],keyPattern:"Einerseits..., andererseits...; Zusammenfassend..."}
],
B2:[
{title:"Debate & Argumentation",rules:["Concede then counter: Zwar..., aber...; Einerseits..., andererseits...","Soften disagreement: Ich verstehe den Punkt, wuerde aber ergaenzen...","Strong claims: Es steht ausser Frage, dass...","'zumal', 'zudem', 'ferner' add weight to arguments."],examples:[{src:"Zwar ist das teuer, aber es lohnt sich.",tr:"Admittedly that is expensive, but it is worth it."},{src:"Es steht ausser Frage, dass wir handeln muessen.",tr:"It is beyond question that we must act."},{src:"Ich sehe den Punkt, wuerde aber ergaenzen, dass...",tr:"I see the point, but would add that..."}],keyPattern:"Zwar + Statement, aber + Counterpoint."},
{title:"Passive Voice & Register",rules:["Vorgangspassiv: werden + Partizip II (process). Zustandspassiv: sein + Partizip II (state/result).","Passive with modals: Das muss gemacht werden.","Choose register consciously: erhalten (formal) vs. kriegen (colloquial).","Man-constructions are a flexible passive alternative: Man sagt, dass..."],examples:[{src:"Der Vertrag wird unterschrieben.",tr:"The contract is being signed."},{src:"Der Vertrag ist unterschrieben.",tr:"The contract is signed (done)."},{src:"Das Problem muss geloest werden.",tr:"The problem must be solved."}],keyPattern:"Object + werden + ... + Partizip II: Das Haus wird gebaut."},
{title:"Complex Connectors & Structure",rules:["Two-part connectors: nicht nur... sondern auch...; sowohl... als auch...; entweder... oder...","'je... desto...' expresses proportion (je + comparative, desto + comparative).","'wohingegen' and 'waehrend' express contrast.","Nominalization makes writing more formal: das Lernen, die Entwicklung."],examples:[{src:"Je mehr ich uebe, desto besser werde ich.",tr:"The more I practise, the better I get."},{src:"Sie spricht sowohl Deutsch als auch Franzoesisch.",tr:"She speaks both German and French."},{src:"Er arbeitet, wohingegen sie studiert.",tr:"He works, whereas she studies."}],keyPattern:"Je + comparative, desto + comparative: Je frueher, desto besser."},
{title:"News Analysis & Abstract Ideas",rules:["Attribute sources: laut Angaben..., einem Bericht zufolge...","Abstract nouns from adjectives: gerecht -> Gerechtigkeit; nachhaltig -> Nachhaltigkeit.","Describe trends: der Anstieg, der Rueckgang, die Entwicklung.","Distinguish fact from opinion in reporting language."],examples:[{src:"Einem Bericht zufolge steigt die Zahl.",tr:"According to a report, the number is rising."},{src:"Die Nachhaltigkeit spielt eine grosse Rolle.",tr:"Sustainability plays a major role."},{src:"Es gab einen deutlichen Rueckgang.",tr:"There was a clear decline."}],keyPattern:"Laut + dative / einem Bericht zufolge + statement."},
{title:"Negotiation, Presentation & Review",rules:["Negotiation phrases: Wir koennten uns auf... einigen; unter der Bedingung, dass...","Presentation signposts: Zunaechst..., Im naechsten Schritt..., Abschliessend...","Give constructive feedback with Konjunktiv II: koennte staerker sein.","Reference visuals: Wie Sie der Grafik entnehmen koennen..."],examples:[{src:"Wir koennten uns auf einen Kompromiss einigen.",tr:"We could agree on a compromise."},{src:"Wie Sie der Grafik entnehmen koennen, steigt der Umsatz.",tr:"As you can see from the graph, revenue is rising."},{src:"Das Argument koennte staerker belegt werden.",tr:"The argument could be better supported."}],keyPattern:"Zunaechst..., dann..., abschliessend..."}
],
C1:[
{title:"Nuance & Subtle Meaning",rules:["Modal particles (doch, mal, ja, eben, halt) add tone but rarely translate directly.","'gewissermassen', 'sozusagen' soften or qualify statements.","'kaum' (hardly) and 'durchaus' (quite/certainly) fine-tune intensity.","Word order shifts emphasis: the position-1 element is highlighted."],examples:[{src:"Das ist durchaus moeglich.",tr:"That is quite possible."},{src:"Komm doch mal vorbei!",tr:"Do come by sometime!"},{src:"Er hat gewissermassen recht.",tr:"He is right, in a sense."}],keyPattern:"Modal particle inside the sentence: Das ist ja interessant."},
{title:"Academic Reading & Precision",rules:["Academic framing: Die vorliegende Studie zeigt...; Im Mittelpunkt steht...","Genitive prepositions: aufgrund, trotz, waehrend, innerhalb (+ Genitiv).","Extended participial attributes pack information before a noun.","Footnotes (Fussnoten) and citations support claims."],examples:[{src:"Aufgrund der Ergebnisse ziehen wir folgende Schluesse.",tr:"Based on the results we draw the following conclusions."},{src:"Die vorliegende Studie untersucht den Einfluss von...",tr:"The present study examines the influence of..."},{src:"Trotz der Kritik blieb das Modell bestehen.",tr:"Despite the criticism the model persisted."}],keyPattern:"aufgrund/trotz/waehrend + Genitiv: trotz des Regens."},
{title:"Idioms & Stylistic Choice",rules:["Idioms carry cultural meaning: 'Das ist nicht mein Bier' = not my concern.","'jemandem auf den Keks gehen' = to annoy someone (colloquial).","Match idiom register to context - avoid slang in formal writing.","Parataxis (short clauses) vs. hypotaxis (subordinated) shapes rhythm."],examples:[{src:"Das ist nicht mein Bier.",tr:"That is not my concern."},{src:"Du gehst mir auf den Keks.",tr:"You are getting on my nerves."},{src:"Ich verstehe nur Bahnhof.",tr:"I do not understand a thing."}],keyPattern:"Fixed idiom, used whole: Das geht auf keine Kuhhaut."},
{title:"Long-form Listening & Summary",rules:["Track the 'roter Faden' (main thread) through a long lecture.","Recognize discourse markers that signal structure: einerseits, folglich, abschliessend.","Plusquamperfekt marks events before another past event.","A neutral summary reports without personal evaluation."],examples:[{src:"Nachdem er gesprochen hatte, stellte man Fragen.",tr:"After he had spoken, questions were asked."},{src:"Der Autor argumentiert, dass...",tr:"The author argues that..."},{src:"Folglich ergibt sich ein neues Bild.",tr:"Consequently a new picture emerges."}],keyPattern:"Nachdem + Plusquamperfekt, ... Praeteritum."},
{title:"Formal Writing, Speaking & Editing",rules:["Formal letters open 'Sehr geehrte Damen und Herren,' and close 'Hochachtungsvoll' or 'Mit freundlichen Gruessen'.","Use 'anbei' / 'beigefuegt' for attachments.","In speech, hedge with 'sozusagen', 'gewissermassen', 'grob gesagt'.","Edit out fillers (eigentlich, irgendwie) and redundant nominalizations."],examples:[{src:"Anbei sende ich Ihnen die Unterlagen.",tr:"Please find the documents attached."},{src:"Grob gesagt, geht es um drei Punkte.",tr:"Roughly speaking, it is about three points."},{src:"Hochachtungsvoll, Dr. Weber.",tr:"Yours faithfully, Dr. Weber."}],keyPattern:"Sehr geehrte... + body + Mit freundlichen Gruessen."}
],
C3:[
{title:"Near-native Tone & Flexibility",rules:["Vorfeld (position 1) choice steers emphasis and information flow.","Native rhythm favors balanced clauses and natural particle use.","'eh', 'ohnehin', 'sowieso' add idiomatic emphasis.","Read the pragmatic situation: irony, politeness, distance."],examples:[{src:"Das wollte ich ohnehin sagen.",tr:"I was going to say that anyway."},{src:"Genau das meine ich.",tr:"That is exactly what I mean."},{src:"Darum geht es mir gar nicht.",tr:"That is not at all my point."}],keyPattern:"Marked Vorfeld for emphasis: Diesen Punkt finde ich entscheidend."},
{title:"Dialect Awareness",rules:["Hochdeutsch is the standard; regional varieties differ in sound and vocabulary.","Bavarian/Austrian: Servus, Gruess Gott; Northern: Moin.","Recognize but do not necessarily produce strong dialect.","Swiss German diverges significantly in pronunciation and lexis."],examples:[{src:"Gruess Gott! (Sueddeutschland)",tr:"Hello! (Southern Germany)"},{src:"Moin! (Norddeutschland)",tr:"Hi! (Northern Germany)"},{src:"Das ist Hochdeutsch.",tr:"That is standard German."}],keyPattern:"Regional greeting marks origin: Servus / Moin / Gruess Gott."},
{title:"Rhetorical Control",rules:["Klimax builds from weak to strong for impact.","Anapher repeats an opening word across clauses for rhythm.","Rhetorical questions guide the audience.","Parenthese inserts asides without breaking the main line."],examples:[{src:"Wir kamen, wir sahen, wir siegten.",tr:"We came, we saw, we conquered."},{src:"Ist das gerecht? Ist das klug? Ist das noetig?",tr:"Is that fair? Is that wise? Is that necessary?"},{src:"Das Ergebnis - und das ist entscheidend - ueberzeugt.",tr:"The result - and this is decisive - is convincing."}],keyPattern:"Anaphora: Repeat the opening word for rhythm."},
{title:"Literary Texture",rules:["Stylistic devices: Metapher, Synaesthesie, Personifikation, transferred epithet.","Enjambement carries a clause across a line break in poetry.","Register and lexical choice create atmosphere.","Read between the lines for subtext and connotation."],examples:[{src:"Ein leises Blau lag ueber dem Tal.",tr:"A quiet blue lay over the valley."},{src:"Die Zeit kroch dahin.",tr:"Time crept along."},{src:"Sein Wort war Gesetz.",tr:"His word was law."}],keyPattern:"Sensory transfer (synaesthesia): ein warmer Klang."},
{title:"Specialized & Masterclass Tasks",rules:["Domain lexis: legal (der Rechtsbeistand), economic (das Bruttoinlandsprodukt), academic (die Hypothese).","Translate untranslatables by explanation or loan: Schadenfreude, Fernweh.","Distinguish Uebersetzen (written) from Dolmetschen (spoken).","Editing at this level preserves register, intent, and nuance simultaneously."],examples:[{src:"Das Bruttoinlandsprodukt waechst um zwei Prozent.",tr:"The gross domestic product grows by two percent."},{src:"Schadenfreude laesst sich kaum uebersetzen.",tr:"Schadenfreude can hardly be translated."},{src:"Der Sachverhalt ist juristisch komplex.",tr:"The state of affairs is legally complex."}],keyPattern:"Precision lexis + preserved register across the whole text."}
]
};

const deBooks = [
{level:"A1",title:"Nicos Weg (A1)",author:"Deutsche Welle",type:"Online course",desc:"Free video-based course with graded dialogues and exercises - ideal first contact with German."},
{level:"A1",title:"Schritte International Neu A1",author:"Hueber Verlag",type:"Textbook",desc:"Widely used classroom coursebook with audio, clear grammar boxes and everyday vocabulary."},
{level:"A1",title:"Erste Geschichten fuer Deutschlerner",author:"Andre Klein",type:"Graded reader",desc:"Very short illustrated stories (Dino lernt Deutsch series) written for absolute beginners."},
{level:"A2",title:"Schritte International Neu A2",author:"Hueber Verlag",type:"Textbook",desc:"Continues the Schritte method with longer texts, past tense and travel situations."},
{level:"A2",title:"Café in Berlin",author:"Andre Klein",type:"Graded reader",desc:"Episodic A2 reader following daily life in Berlin, with vocabulary lists per chapter."},
{level:"A2",title:"Grammatik aktiv A1-B1",author:"Cornelsen",type:"Grammar workbook",desc:"Practice-focused grammar with a page of theory and a page of exercises throughout."},
{level:"B1",title:"Aspekte neu B1+",author:"Klett",type:"Textbook",desc:"Theme-based coursebook bridging to independent use, with authentic media texts."},
{level:"B1",title:"Der Vorleser",author:"Bernhard Schlink",type:"Novel",desc:"Modern classic with accessible prose - a strong first 'real' German novel for upper-B1."},
{level:"B1",title:"Hammer's German Grammar (B1-C1)",author:"Durrell",type:"Reference grammar",desc:"Comprehensive English-language reference to consult as structures get complex."},
{level:"B2",title:"Aspekte neu B2",author:"Klett",type:"Textbook",desc:"Advanced coursebook with debate, register and longer argumentative writing tasks."},
{level:"B2",title:"Tschick",author:"Wolfgang Herrndorf",type:"Novel",desc:"Fast, funny road-trip novel in lively contemporary German - very popular with learners."},
{level:"B2",title:"Sicher! B2",author:"Hueber Verlag",type:"Textbook",desc:"Skill-building course emphasizing nuanced speaking, negotiation and presentation."},
{level:"C1",title:"Erkundungen C1",author:"Schubert Verlag",type:"Textbook",desc:"Dense C1 coursebook with sophisticated texts, idioms and precise grammar work."},
{level:"C1",title:"Die Verwandlung",author:"Franz Kafka",type:"Literature",desc:"Short but stylistically rich text for analysing literary German and nuance."},
{level:"C1",title:"Der Dativ ist dem Genitiv sein Tod",author:"Bastian Sick",type:"Language essays",desc:"Witty essays on German usage that sharpen feeling for register and correctness."},
{level:"C3",title:"Mittelpunkt neu C2",author:"Klett",type:"Textbook",desc:"Top-level course preparing for near-native command across academic and professional registers."},
{level:"C3",title:"Die Blechtrommel",author:"Guenter Grass",type:"Literature",desc:"Linguistically demanding Nobel-laureate novel for mastering literary texture."},
{level:"C3",title:"Duden - Das Stilwoerterbuch",author:"Dudenredaktion",type:"Reference",desc:"Style dictionary showing idiomatic word combinations for truly native-like writing."}
];
