const deTaskQBank = {
A1:[
[{q:"What does 'Guten Morgen' mean?",opts:["Good evening","Good night","Good morning","Goodbye"],a:2},{q:"Which greeting is used midday?",opts:["Guten Morgen","Guten Tag","Gute Nacht","Tschuess"],a:1},{q:"How do you say 'Nice to meet you'?",opts:["Auf Wiedersehen","Entschuldigung","Freut mich","Bitte"],a:2},{q:"'Wie geht es Ihnen?' is the ___ form.",opts:["informal","formal","plural only","written only"],a:1},{q:"A casual 'Hi' among friends is:",opts:["Hallo","Sehr geehrte","Mahlzeit","Gute Besserung"],a:0}],
[{q:"Which letter pair sounds like 'ts'?",opts:["sch","ch","tz","st"],a:2},{q:"'ue' (ü) sounds most like which English sound?",opts:["oo in boot","ee with rounded lips","ay in day","i in bit"],a:1},{q:"What does 'ss' (ß) represent?",opts:["a soft b","a double s sound","a silent letter","an r sound"],a:1},{q:"'sch' is pronounced like:",opts:["sh","sk","s-ch","tch"],a:0},{q:"The letter 'w' in German sounds like English:",opts:["w","v","f","b"],a:1}],
[{q:"What is 'zwanzig' in English?",opts:["12","20","22","102"],a:1},{q:"How do you say 47 in German?",opts:["siebenundvierzig","vierundsieben","siebenvier","viersieben"],a:0},{q:"Which is correct for 21?",opts:["zweigezehn","einundzwanzig","zwanzigein","zweiunddrei"],a:1},{q:"'hundert' means:",opts:["10","100","1000","11"],a:1},{q:"'fuenfzehn' is:",opts:["5","50","15","55"],a:2}],
[{q:"Which article goes with 'Tisch' (table)?",opts:["die","das","der","ein"],a:2},{q:"Which article goes with 'Frau' (woman)?",opts:["der","das","die","dem"],a:2},{q:"'Kind' (child) takes which article?",opts:["der","die","das","ein"],a:2},{q:"The plural definite article for all genders is:",opts:["der","die","das","den"],a:1},{q:"'Buch' (book) takes which article?",opts:["der","die","das","dem"],a:2}],
[{q:"Which is correct? 'Du ___ Deutsch.'",opts:["lerne","lernst","lernt","lernen"],a:1},{q:"'wir' takes which verb ending?",opts:["-st","-t","-en","-e"],a:2},{q:"Conjugate 'haben' for 'er':",opts:["habt","habe","hat","haben"],a:2},{q:"'ich ___' (sein):",opts:["bist","bin","ist","sind"],a:1},{q:"'ihr ___ Deutsch' (sprechen):",opts:["sprecht","sprichst","spricht","sprechen"],a:0}],
[{q:"How do you politely order food?",opts:["Ich will ein Bier","Ich haette gern einen Kaffee","Gib mir Wasser","Bring Kaffee"],a:1},{q:"'Zahlen bitte' means:",opts:["The menu please","Can I order?","The bill please","Excuse me"],a:2},{q:"'Was empfehlen Sie?' means:",opts:["What is the special?","What do you recommend?","Do you have a table?","Is service included?"],a:1},{q:"'die Speisekarte' is the:",opts:["bill","menu","waiter","kitchen"],a:1},{q:"'Guten Appetit!' means:",opts:["Cheers!","Enjoy your meal!","The bill, please!","Welcome!"],a:1}],
[{q:"'die Schwester' means:",opts:["brother","mother","sister","aunt"],a:2},{q:"'der Grossvater' means:",opts:["uncle","grandfather","father","stepfather"],a:1},{q:"German for 'cousin' (female)?",opts:["die Kusine","die Schwester","die Nichte","die Tante"],a:0},{q:"'die Eltern' means:",opts:["the children","the parents","the grandparents","the siblings"],a:1},{q:"'der Sohn' means:",opts:["son","daughter","nephew","brother"],a:0}],
[{q:"'aufstehen' means:",opts:["to eat","to sleep","to get up","to go out"],a:2},{q:"'fruehstuecken' means:",opts:["to shower","to have breakfast","to drive","to work"],a:1},{q:"'einschlafen' means:",opts:["to wake up","to dream","to fall asleep","to rest"],a:2},{q:"'arbeiten' means:",opts:["to play","to work","to wait","to walk"],a:1},{q:"'nach Hause gehen' means:",opts:["to go shopping","to go home","to go out","to go to work"],a:1}],
[{q:"'Wo wohnst du?' asks about:",opts:["your name","where you live","your age","what you do"],a:1},{q:"Which word asks 'why'?",opts:["wer","was","warum","wann"],a:2},{q:"'Wie viel kostet das?' means:",opts:["What time is it?","How much does it cost?","Where is it?","Is it open?"],a:1},{q:"'Wer ist das?' asks:",opts:["What is that?","Where is that?","Who is that?","When is that?"],a:2},{q:"To ask someone's name formally:",opts:["Wie heisst du?","Wie heissen Sie?","Wer bist du?","Was machst du?"],a:1}],
[{q:"After 'Wie geht es Ihnen?' a polite response is:",opts:["Ich weiss nicht","Danke, gut. Und Ihnen?","Nein","Sprechen Sie Englisch?"],a:1},{q:"'Koennen Sie das wiederholen?' means:",opts:["Can you help me?","Can you repeat that?","Do you speak slower?","Where is the exit?"],a:1},{q:"Which farewell is most formal?",opts:["Tschuess","Ciao","Auf Wiedersehen","Bis bald"],a:2},{q:"'Entschuldigung, wo ist...?' begins a:",opts:["complaint","polite request for directions","greeting","goodbye"],a:1},{q:"'Bis morgen!' means:",opts:["See you tomorrow!","Good morning!","Until later!","Goodbye forever!"],a:0}]
],
A2:[
[{q:"Which auxiliary is used for 'fahren' in Perfekt?",opts:["haben","sein","werden","tun"],a:1},{q:"Correct Perfekt of 'essen'?",opts:["habe gegessen","habe geesst","bin gegessen","habe geessen"],a:0},{q:"'Gestern ___ ich ins Kino gegangen.'",opts:["habe","bin","war","wurde"],a:1},{q:"Past participle of 'machen':",opts:["gemacht","gemachen","machte","gemecht"],a:0},{q:"'Ich habe Deutsch ___.' (lernen)",opts:["gelernt","gelernen","lernte","lernt"],a:0}],
[{q:"'Geradeaus' means:",opts:["turn left","straight ahead","turn right","go back"],a:1},{q:"'Die erste Strasse links' means:",opts:["the second street right","the first street on the left","go straight","the next corner"],a:1},{q:"'Wie komme ich zum Bahnhof?' means:",opts:["Is the station far?","How do I get to the station?","Where is the bus stop?","How long does it take?"],a:1},{q:"'rechts abbiegen' means:",opts:["turn left","turn right","go straight","stop"],a:1},{q:"'gegenueber' means:",opts:["next to","opposite","behind","far"],a:1}],
[{q:"'Das ist mir zu teuer' means:",opts:["I'll take it","That's too expensive for me","Do you have another size?","It fits perfectly"],a:1},{q:"'Haben Sie das in Groesse M?' means:",opts:["Do you have the receipt?","Where is the changing room?","Do you have this in size M?","Can I pay by card?"],a:2},{q:"'Ich schaue mich nur um' means:",opts:["I'll buy two","I'm just looking","Can you help me?","I'd like to return this"],a:1},{q:"'im Angebot' means:",opts:["sold out","on offer/sale","too expensive","second-hand"],a:1},{q:"'Kann ich mit Karte zahlen?' asks about:",opts:["cash only","paying by card","a discount","the receipt"],a:1}],
[{q:"Which verb is separable?",opts:["verstehen","beschreiben","anrufen","erzaehlen"],a:2},{q:"'Er ___ um 8 Uhr ___.' (aufwachen)",opts:["wacht/auf","aufwacht/ ","wache/auf","wake/auf"],a:0},{q:"Where does the prefix go in a main clause?",opts:["stays attached","goes to the end","moves to position 1","drops entirely"],a:1},{q:"'einkaufen': Ich kaufe im Supermarkt ___.",opts:["ein","aus","auf","ab"],a:0},{q:"In a subordinate clause, a separable verb:",opts:["splits","stays together at the end","moves to start","disappears"],a:1}],
[{q:"'Ich muss jetzt gehen.' The infinitive goes:",opts:["to position 1","to the end","after muss","before ich"],a:1},{q:"Which modal expresses ability?",opts:["muessen","wollen","koennen","sollen"],a:2},{q:"Correct: 'Du ___ hier nicht rauchen.'",opts:["darfst","kannst","sollst","musst"],a:0},{q:"'moechte' is the polite form of:",opts:["muessen","wollen","koennen","duerfen"],a:1},{q:"'Wir ___ Deutsch lernen.' (want to)",opts:["wollen","muessen","koennen","sollen"],a:0}],
[{q:"'Haben Sie am Dienstag Zeit?' means:",opts:["Is Tuesday good for you?","What time on Tuesday?","Is Tuesday a holiday?","When is Tuesday?"],a:0},{q:"'Der Termin ist um halb drei.' means:",opts:["at 3:30","at 2:30","at 3:00","at half past three pm"],a:1},{q:"'Ich muss leider absagen' means:",opts:["I need to reschedule","I unfortunately have to cancel","I'm running late","I'll be there early"],a:1},{q:"'Passt es Ihnen um 10 Uhr?' asks if:",opts:["10 o'clock suits you","it is 10 o'clock","you are late","the meeting is over"],a:0},{q:"'einen Termin vereinbaren' means:",opts:["to cancel an appointment","to make an appointment","to be late","to arrive early"],a:1}],
[{q:"'Es regnet' means:",opts:["It's snowing","It's sunny","It's raining","It's cloudy"],a:2},{q:"'bewoelkt' means:",opts:["windy","sunny","foggy","cloudy"],a:3},{q:"'Wie wird das Wetter morgen?' means:",opts:["What is the weather now?","What will the weather be tomorrow?","Is it cold today?","What is the forecast?"],a:1},{q:"'Es ist heiss' means:",opts:["It's cold","It's hot","It's wet","It's windy"],a:1},{q:"'der Schnee' means:",opts:["rain","snow","sun","wind"],a:1}],
[{q:"'Mit freundlichen Gruessen' is used:",opts:["at the start of formal email","at the end of a formal email","in informal messages","in spoken farewells"],a:1},{q:"'Sehr geehrte Damen und Herren' translates as:",opts:["Hi everyone","Dear Sir or Madam","Hello friends","Dear colleagues"],a:1},{q:"'Ich beziehe mich auf Ihre E-Mail vom...' means:",opts:["I am replying immediately","I refer to your email of...","I am forwarding your message","I have not received your email"],a:1},{q:"An informal email might open with:",opts:["Sehr geehrter Herr","Hallo Tom,","Hochachtungsvoll","Anbei"],a:1},{q:"'Anbei finden Sie...' means:",opts:["Please find attached...","I am writing because...","Best regards...","See you soon..."],a:0}],
[{q:"'Wo ist der naechste Geldautomat?' means:",opts:["Where is the nearest bus stop?","Where is the nearest ATM?","Where is the hotel?","Where is the nearest pharmacy?"],a:1},{q:"'Einmal nach Muenchen, bitte.' means:",opts:["One return to Munich","One ticket to Munich, please","First class to Munich","One hotel room in Munich"],a:1},{q:"'Hat der Zug Verspaetung?' means:",opts:["Is the train fast?","Does the train have a dining car?","Is the train delayed?","Has the train departed?"],a:2},{q:"'umsteigen' means:",opts:["to board","to change trains","to arrive","to buy a ticket"],a:1},{q:"'das Gepaeck' means:",opts:["the ticket","the luggage","the platform","the seat"],a:1}],
[{q:"For retelling a story in written German, which tense is most common?",opts:["Perfekt","Praesens","Praeteritum","Futur"],a:2},{q:"'Er erzaehlte, dass...' introduces:",opts:["a question","indirect speech","a command","a comparison"],a:1},{q:"'Zum Schluss' means:",opts:["At first","On the other hand","In the middle","At the end / In conclusion"],a:3},{q:"'Zuerst... dann... danach...' are used to:",opts:["compare","sequence events","ask questions","negate"],a:1},{q:"'ploetzlich' means:",opts:["slowly","suddenly","finally","never"],a:1}]
],
B1:[
[{q:"Which phrase introduces a personal opinion?",opts:["Es ist bekannt, dass","Meiner Meinung nach","Laut Statistik","Man sagt, dass"],a:1},{q:"'Ich bin der Ansicht, dass...' means:",opts:["It is said that...","It is a fact...","I am of the opinion that...","Studies show that..."],a:2},{q:"A more formal way to say 'I think':",opts:["Ich denke","Ich glaube","Ich bin der Meinung","Ich finde"],a:2},{q:"'Da stimme ich (nicht) zu' expresses:",opts:["a question","agreement/disagreement","a wish","a command"],a:1},{q:"'Ich finde, dass...' sends the verb:",opts:["to position 1","to position 2","to the end of the clause","nowhere"],a:2}],
[{q:"In a 'weil' clause, the verb goes:",opts:["to position 2","to the start","to the end","stays in position 1"],a:2},{q:"Which conjunction creates a subordinate clause?",opts:["und","aber","denn","obwohl"],a:3},{q:"The verb moves to the END in a clause introduced by:",opts:["aber","oder","denn","weil"],a:3},{q:"'als' vs 'wenn': 'als' refers to:",opts:["a repeated action","a single past event","the future","a condition"],a:1},{q:"Relative pronoun for 'das Buch, ___ ich lese':",opts:["der","die","das","dem"],a:2}],
[{q:"'die Bewerbung' means:",opts:["the salary","the application","the promotion","the deadline"],a:1},{q:"'Ich bin fuer das Projekt verantwortlich' means:",opts:["I am interested in the project","I am responsible for the project","I created the project","I finished the project"],a:1},{q:"'das Vorstellungsgespraech' is:",opts:["a pay raise","a resignation letter","a job interview","a work contract"],a:2},{q:"'der Lebenslauf' is the:",opts:["cover letter","CV/resume","contract","reference"],a:1},{q:"'Ueberstunden machen' means:",opts:["to take a break","to work overtime","to quit","to be promoted"],a:1}],
[{q:"'die Schlagzeile' means:",opts:["a documentary","a headline","an advertisement","an editorial"],a:1},{q:"'laut einem Bericht' means:",opts:["according to a report","before the report","despite the report","without a report"],a:0},{q:"Which verb signals reported information?",opts:["erklaeren","hoeren","berichten","fuehlen"],a:2},{q:"'die Sendung' means:",opts:["the newspaper","the TV/radio programme","the headline","the journalist"],a:1},{q:"To check understanding while listening, focus on:",opts:["every single word","key words and context","only the ending","the background music"],a:1}],
[{q:"'Du solltest mehr schlafen.' expresses:",opts:["a command","advice","a fact","a question"],a:1},{q:"'Ich wuerde empfehlen...' means:",opts:["I refuse to...","I demand that...","I would recommend...","I regret that..."],a:2},{q:"'An deiner Stelle wuerde ich...' means:",opts:["If I were you, I would...","You should never...","Instead of that...","On behalf of you..."],a:0},{q:"'sollte' is the ___ form of sollen.",opts:["present","Konjunktiv II","past","future"],a:1},{q:"'Es waere besser, wenn...' means:",opts:["It is better that...","It would be better if...","It was better when...","It will never be better..."],a:1}],
[{q:"'Ich werde naechstes Jahr reisen.' uses which tense?",opts:["Perfekt","Praeteritum","Futur I","Konjunktiv II"],a:2},{q:"'Ich habe vor, zu studieren.' means:",opts:["I used to study","I intend to study","I finished studying","I should study"],a:1},{q:"'demnaechst' means:",opts:["recently","forever","soon","rarely"],a:2},{q:"Futur I is formed with:",opts:["haben + participle","werden + infinitive","sein + participle","modal + past"],a:1},{q:"'Ich plane, eine Reise zu machen' expresses:",opts:["a past event","an intention","a regret","a command"],a:1}],
[{q:"Indirect speech marker in German:",opts:["ob","weil","dass","obwohl"],a:2},{q:"'Er sagte, er ___ muede.'",opts:["ist","sei","war","waere"],a:1},{q:"'Sie fragte, ob ich kommen ___.'",opts:["werde","wuerde","komme","kaeme"],a:1},{q:"Konjunktiv I is mainly used for:",opts:["wishes","reported speech","conditions","commands"],a:1},{q:"'Man sagt, dass...' is a way to:",opts:["give an order","report general claims","express a wish","ask a question"],a:1}],
[{q:"'Es liegt daran, dass...' means:",opts:["It is unrelated to...","It follows that...","The reason is that...","It is possible that..."],a:2},{q:"'eine Loesung finden' means:",opts:["to cause a problem","to find a solution","to avoid an issue","to discuss options"],a:1},{q:"'zunaechst' means:",opts:["finally","in addition","first of all","however"],a:2},{q:"'Das Problem besteht darin, dass...' means:",opts:["The problem consists in that...","The problem is solved...","There is no problem...","The problem disappears..."],a:0},{q:"'einen Kompromiss schliessen' means:",opts:["to start a fight","to reach a compromise","to give up","to win"],a:1}],
[{q:"A German essay typically opens with:",opts:["a personal anecdote","a thesis statement","a dictionary definition","a list of examples"],a:1},{q:"'Einerseits... andererseits...' is used to:",opts:["list items","show contrast","give examples","conclude"],a:1},{q:"'Zusammenfassend laesst sich sagen...' means:",opts:["To begin with...","By contrast...","In summary...","For example..."],a:2},{q:"The three parts of an essay are:",opts:["title, body, image","Einleitung, Hauptteil, Schluss","intro, intro, intro","question, answer, question"],a:1},{q:"'Beispielsweise' means:",opts:["in conclusion","for example","however","therefore"],a:1}],
[{q:"'Erzaehlen Sie von sich.' means:",opts:["Where do you work?","Tell me about yourself.","What are your weaknesses?","Why do you want this job?"],a:1},{q:"'Meine Staerken sind...' means:",opts:["My goals are...","My weaknesses are...","My strengths are...","My experience is..."],a:2},{q:"'Haben Sie noch Fragen?' means:",opts:["Do you have references?","Are you available now?","Do you have any questions?","Can you start immediately?"],a:2},{q:"'Warum bewerben Sie sich?' asks:",opts:["When can you start?","Why are you applying?","What is your salary?","Where do you live?"],a:1},{q:"A good interview answer should be:",opts:["very long and vague","concrete with examples","one word only","unrelated to the question"],a:1}]
],
B2:[
[{q:"'Das laesst sich nicht von der Hand weisen' means:",opts:["That cannot be denied","That should be avoided","That is irrelevant","That needs clarification"],a:0},{q:"To concede a point in German debate, use:",opts:["Zugegeben, aber...","Nein, niemals...","Absolut falsch...","Wie gesagt..."],a:0},{q:"'im Grunde genommen' means:",opts:["on the other hand","fundamentally / basically","by contrast","in addition"],a:1},{q:"'Es steht ausser Frage, dass...' means:",opts:["It is doubtful that...","It is beyond question that...","It is irrelevant that...","It is unclear that..."],a:1},{q:"'Ich teile diese Ansicht (nicht)' expresses:",opts:["a greeting","(dis)agreement with a view","a request","a summary"],a:1}],
[{q:"Correct Vorgangspassiv:",opts:["Das Buch wird gelesen","Das Buch ist gelesen","Das Buch hat gelesen","Das Buch wurde lesen"],a:0},{q:"Zustandspassiv of 'abschliessen':",opts:["ist abgeschlossen","wird abgeschlossen","hat abgeschlossen","abschliesst"],a:0},{q:"'Von wem wird das Projekt geleitet?' uses:",opts:["Aktiv","Vorgangspassiv","Zustandspassiv","Modalpassiv"],a:1},{q:"Vorgangspassiv is formed with:",opts:["sein + Partizip II","werden + Partizip II","haben + Partizip II","Partizip II alone"],a:1},{q:"Passive with a modal: 'Das muss ___ werden.'",opts:["gemacht","machen","macht","zu machen"],a:0}],
[{q:"'nicht nur... sondern auch...' means:",opts:["neither... nor...","not only... but also...","either... or...","if... then..."],a:1},{q:"'Je mehr du uebst, desto besser wirst du.' shows:",opts:["contrast","proportion","concession","reason"],a:1},{q:"'wohingegen' is used to:",opts:["add information","show condition","express contrast","give examples"],a:2},{q:"'sowohl... als auch...' means:",opts:["both... and...","neither... nor...","either... or...","not only..."],a:0},{q:"'entweder... oder...' means:",opts:["both... and...","either... or...","neither... nor...","although"],a:1}],
[{q:"'laut Angaben des Ministeriums' means:",opts:["against the ministry's data","according to the ministry's data","beyond the ministry's statement","following the ministry report"],a:1},{q:"'der Rueckgang' means:",opts:["an increase","a recovery","a decline","an announcement"],a:2},{q:"'Die Reaktionen fielen gemischt aus.' means:",opts:["Reactions were positive","Reactions were negative","Reactions were mixed","There were no reactions"],a:2},{q:"'der Anstieg' means:",opts:["the rise","the fall","the report","the cause"],a:0},{q:"To distinguish fact from opinion, look for:",opts:["emotional adjectives vs. data","only the headline","the photo","the date"],a:0}],
[{q:"Which word is MOST formal?",opts:["kriegen","bekommen","erhalten","nehmen"],a:2},{q:"'hiermit' is used in:",opts:["casual conversation","formal documents","academic slang","media headlines"],a:1},{q:"'ich lass dich wissen' is:",opts:["formal","technical","colloquial","literary"],a:2},{q:"Register means the level of:",opts:["volume","formality","speed","accent"],a:1},{q:"'meinereiner' is an example of ___ register.",opts:["very formal","colloquial/regional","academic","legal"],a:1}],
[{q:"'Wir koennten uns auf einen Kompromiss einigen.' means:",opts:["We reject the proposal","We could agree on a compromise","We demand a different solution","We have no flexibility"],a:1},{q:"'das ist nicht verhandelbar' means:",opts:["that is negotiable","that is not negotiable","that depends","we can discuss this"],a:1},{q:"'unter Vorbehalt' means:",opts:["unconditionally","without notice","with reservation / conditionally","formally agreed"],a:2},{q:"'einen Vorschlag machen' means:",opts:["to reject an offer","to make a proposal","to sign a contract","to end talks"],a:1},{q:"'auf halbem Weg entgegenkommen' means:",opts:["to refuse entirely","to meet halfway","to leave","to insist"],a:1}],
[{q:"Which is a nominalized verb?",opts:["der Lauf","laufen","gelaufen","lief"],a:0},{q:"'die Nachhaltigkeit' relates to:",opts:["innovation","sustainability","productivity","efficiency"],a:1},{q:"Abstract noun from 'gerecht':",opts:["die Gerechte","die Gerechtigkeit","das Gerechtsein","die Gerechtheid"],a:1},{q:"Nominalizing a verb often takes the article:",opts:["der","die","das","den"],a:2},{q:"'die Freiheit' is an abstract noun from:",opts:["frei","Freude","Frieden","fragen"],a:0}],
[{q:"A Begruendung supports a claim with:",opts:["examples","counter-arguments","evidence/reasons","summaries"],a:2},{q:"'Die These lautet...' introduces:",opts:["a conclusion","a main claim/thesis","a supporting detail","a question"],a:1},{q:"'Dafuer spricht...' means:",opts:["Against this is...","The problem is...","In favor of this is...","Despite this..."],a:2},{q:"'Dagegen spricht...' means:",opts:["In favor of this...","Against this is...","Therefore...","For example..."],a:1},{q:"A strong argument structure is:",opts:["claim - reason - example","example only","claim only","question - question"],a:0}],
[{q:"To signal end of a section in a presentation:",opts:["Zusammenfassend zu diesem Punkt...","Erstens...","Um ehrlich zu sein...","Lassen Sie mich beginnen..."],a:0},{q:"'Wie Sie der Grafik entnehmen koennen...' means:",opts:["As the graph clearly shows...","As you can see from the graph...","The graph is missing data...","The graph contradicts this..."],a:1},{q:"A rhetorical question in a presentation is used to:",opts:["demand an answer","avoid the topic","engage the audience and signal a point","fill time"],a:2},{q:"'Lassen Sie mich kurz erlaeutern...' means:",opts:["Let me conclude...","Let me briefly explain...","Let me disagree...","Let me leave..."],a:1},{q:"Good presentation signposting helps the audience:",opts:["get confused","follow the structure","ignore the talk","leave early"],a:1}],
[{q:"'Ich wuerde vorschlagen, den Abschnitt zu kuerzen.' means:",opts:["I demand this section be removed","I suggest shortening the section","This section is perfect","I disagree with this section"],a:1},{q:"'Das Argument koennte staerker belegt werden.' means:",opts:["The argument is wrong","The argument needs no evidence","The argument could be better supported","The argument is irrelevant"],a:2},{q:"Constructive feedback always includes:",opts:["only criticism","only praise","specific suggestions for improvement","personal opinions about the author"],a:2},{q:"'Mir gefaellt besonders, dass...' is a way to:",opts:["criticise harshly","give positive feedback","end the talk","ask a question"],a:1},{q:"Good peer feedback is:",opts:["vague and general","specific and respectful","only negative","silent"],a:1}]
],
C1:[
[{q:"'kaum' is best translated as:",opts:["almost","hardly / barely","mostly","slightly"],a:1},{q:"'zwar... aber...' expresses:",opts:["simple addition","concession + contrast","cause + effect","alternative"],a:1},{q:"'gewissermassen' means:",opts:["without doubt","in a sense / to some extent","in contrast","precisely"],a:1},{q:"Modal particle 'doch' mainly adds:",opts:["tense","tone/emphasis","number","case"],a:1},{q:"'durchaus' means:",opts:["never","quite / certainly","hardly","rarely"],a:1}],
[{q:"'Im Mittelpunkt steht...' signals:",opts:["a methodological detail","the central focus of the text","a secondary argument","a conclusion"],a:1},{q:"A 'Fussnote' is:",opts:["a heading","a footnote","a bibliography","an abstract"],a:1},{q:"'die vorliegende Studie zeigt' means:",opts:["The future study will show","The present study shows","The past study showed","The theoretical study predicts"],a:1},{q:"'darlegen' in academic German means:",opts:["to hide","to set out / explain","to ignore","to shorten"],a:1},{q:"Academic citations are used to:",opts:["fill space","support and attribute claims","add humour","confuse readers"],a:1}],
[{q:"'Das ist nicht mein Bier.' means:",opts:["I don't drink beer","That's not my problem / concern","I prefer coffee","That tastes bad"],a:1},{q:"'jemanden uebers Ohr hauen' means:",opts:["to hit someone","to cheat / deceive someone","to wake someone up","to listen to someone"],a:1},{q:"'Tomaten auf den Augen haben' means:",opts:["to have a headache","to be color-blind","to be oblivious to what is happening around you","to cry"],a:2},{q:"'die Daumen druecken' means:",opts:["to give up","to keep one's fingers crossed","to be angry","to be late"],a:1},{q:"Idiomatic register should match the:",opts:["weather","context and audience","time of day","sentence length"],a:1}],
[{q:"Using short sentences in sequence creates:",opts:["ambiguity","a sense of speed and tension","academic tone","subordination"],a:1},{q:"Anaphora is the repetition of:",opts:["a word at the end of clauses","a word at the start of successive clauses","punctuation for emphasis","sentence length"],a:1},{q:"'Der Abend war still. Die Strasse war leer. Niemand sprach.' uses:",opts:["hypotaxis","parataxis","chiasmus","litotes"],a:1},{q:"Hypotaxis is characterised by:",opts:["short equal clauses","subordinated, nested clauses","no verbs","only questions"],a:1},{q:"A long, subordinated sentence tends to feel more:",opts:["urgent","formal/reflective","casual","childish"],a:1}],
[{q:"Genitive of 'der Mann' is:",opts:["dem Mann","den Mann","des Mannes","der Mann"],a:2},{q:"'aufgrund' takes which case?",opts:["Nominativ","Akkusativ","Dativ","Genitiv"],a:3},{q:"'Als er ankam, hatte sie schon gegessen.' The past-before-past verb uses:",opts:["Praeteritum","Perfekt","Plusquamperfekt","Futur II"],a:2},{q:"'trotz' governs which case?",opts:["Akkusativ","Dativ (formally Genitiv)","Nominativ","none"],a:1},{q:"Plusquamperfekt is formed with:",opts:["werden + infinitive","hatte/war + Partizip II","haben + infinitive","sein + infinitive"],a:1}],
[{q:"'der rote Faden' in a lecture means:",opts:["a quotation","an error","the central thread / main argument","a transition"],a:2},{q:"An effective note-taking strategy is:",opts:["writing every word","paraphrasing key ideas","recording only numbers","sketching pictures only"],a:1},{q:"To verify comprehension of a complex passage, you should:",opts:["read a translation","summarize main points in your own words","avoid re-reading","underline every sentence"],a:1},{q:"'die Kernaussage' is:",opts:["a minor detail","the core statement","the introduction","the footnote"],a:1},{q:"Signposting words in a lecture (also, folglich) signal:",opts:["the end of attention","logical structure","background noise","unrelated topics"],a:1}],
[{q:"A Zusammenfassung should:",opts:["include the author's personal opinion","include your personal evaluation","present the text's main ideas neutrally","expand the original argument"],a:2},{q:"'Der Autor argumentiert, dass...' signals:",opts:["a direct quote","attributed reported speech","your personal view","a counterargument"],a:1},{q:"The most common tense in academic German summaries is:",opts:["Praeteritum","Praesens","Futur I","Plusquamperfekt"],a:1},{q:"A critical summary differs from a neutral one by adding:",opts:["more plot","a reasoned evaluation","fictional details","longer quotes"],a:1},{q:"'laut dem Autor' means:",opts:["against the author","according to the author","without the author","despite the author"],a:1}],
[{q:"In a German formal letter, 'Sehr geehrte Damen und Herren' is followed by:",opts:["a comma then uppercase","a comma then lowercase","a period","an exclamation mark"],a:0},{q:"'Anbei sende ich Ihnen...' means:",opts:["I am requesting...","Please find attached...","I am responding to...","I am unable to send..."],a:1},{q:"'ich schick's dir' vs 'ich sende es Ihnen zu' differs in:",opts:["tense","subject","formality","content"],a:2},{q:"Formal closing 'Hochachtungsvoll' is:",opts:["very informal","very formal","a greeting","a question"],a:1},{q:"Formal writing prefers:",opts:["slang","precise, neutral vocabulary","emojis","abbreviations"],a:1}],
[{q:"A filler phrase to gain thinking time in German:",opts:["Auf keinen Fall","Tja, also...","Nein","Vergessen Sie das"],a:1},{q:"'Grob gesagt' means:",opts:["in detail","roughly speaking","to put it bluntly","according to studies"],a:1},{q:"Hedging language in spoken German signals:",opts:["absolute certainty","full commitment","uncertainty or caution","avoidance of verbs"],a:2},{q:"'sozusagen' means:",opts:["so to speak","never","exactly","loudly"],a:0},{q:"Spontaneous speech often uses ___ more than writing.",opts:["footnotes","fillers and self-corrections","passive voice","citations"],a:1}],
[{q:"A Fuellwort (filler word) that should often be cut:",opts:["weil","eigentlich","damit","obwohl"],a:1},{q:"Passive constructions in heavy text should often be replaced with:",opts:["more passive","active voice","nominalized phrases","longer sentences"],a:1},{q:"'doppelt gemoppelt' in editing means:",opts:["adding necessary repetition","using redundant repetition","linking ideas clearly","using formal register"],a:1},{q:"Good editing improves:",opts:["only length","clarity and concision","the font","the colour"],a:1},{q:"Replacing a long nominal phrase with a verb usually makes text:",opts:["heavier","livelier and clearer","longer","incorrect"],a:1}]
],
C3:[
[{q:"Which word order sounds most authentically native?",opts:["Ich gehe nach Hause jetzt","Jetzt gehe ich nach Hause","Ich nach Hause gehe","Gehe ich jetzt nach Hause"],a:1},{q:"'Das zieht sich.' idiomatically means:",opts:["That stretches out literally","That is taking a long time","That pulls at you","That extends very far"],a:1},{q:"Word order flexibility in German emphasizes:",opts:["the subject always","the element in position 1","the verb","the direct object"],a:1},{q:"'ohnehin' means:",opts:["never","anyway","exactly","loudly"],a:1},{q:"Native rhythm relies partly on:",opts:["ignoring particles","natural particle and stress placement","avoiding verbs","only short words"],a:1}],
[{q:"'Mia san mia' is associated with:",opts:["Berlin","Cologne","Bavaria","Hamburg"],a:2},{q:"'Watt?' in Northern German dialect equals:",opts:["Was?","Wohin?","Wann?","Wer?"],a:0},{q:"Standard German is called:",opts:["Hochdeutsch","Plattdeutsch","Berlinerisch","Koelsch"],a:0},{q:"'Gruess Gott' is a greeting from:",opts:["the North","the South (Bavaria/Austria)","Berlin","Hamburg"],a:1},{q:"Swiss German differs from standard mainly in:",opts:["spelling only","pronunciation and vocabulary","punctuation","nothing"],a:1}],
[{q:"A climax (Klimax) in rhetoric moves:",opts:["from strong to weak","from weak to strong","randomly","from abstract to concrete"],a:1},{q:"'Wiederholung' as a rhetorical device creates:",opts:["confusion","irony","emphasis and rhythm","a question"],a:2},{q:"Parenthetical remarks (Parenthesen) are used to:",opts:["conclude","add asides or elaborations","change the topic","introduce a new argument"],a:1},{q:"A rhetorical question is meant to:",opts:["get a literal answer","guide the audience's thinking","fill time","end the talk"],a:1},{q:"'Trikolon' is a rhetorical group of:",opts:["two parts","three parts","four parts","five parts"],a:1}],
[{q:"'Synaesthesie' mixes senses, for example:",opts:["ein hartes Licht","eine schnelle Uhr","ein leises Blau","ein grosses Wort"],a:2},{q:"'eine vergilbte Erinnerung' uses which device?",opts:["personification","transferred epithet","metaphor","onomatopoeia"],a:1},{q:"In lyric poetry, an 'Enjambement' is:",opts:["rhyme at line end","a run-on from one line to the next","a stanza break","a repeated refrain"],a:1},{q:"A 'Metapher' transfers meaning:",opts:["literally","figuratively between unlike things","only in poetry","by sound"],a:1},{q:"'Personifikation' gives human traits to:",opts:["people","non-human things","verbs","numbers"],a:1}],
[{q:"'der Rechtsbeistand' is:",opts:["a judge","legal counsel / lawyer","a jury member","a notary"],a:1},{q:"'das Bruttoinlandsprodukt' is abbreviated as:",opts:["BIP","BRD","BSB","BKA"],a:0},{q:"In economics, 'Inflation' describes:",opts:["a currency revaluation","a drop in prices","a general rise in prices","a trade deficit"],a:2},{q:"'die Hypothese' in research is:",opts:["a proven fact","a testable assumption","a footnote","a conclusion"],a:1},{q:"Specialized vocabulary should be used:",opts:["everywhere","precisely and in context","to confuse readers","never"],a:1}],
[{q:"Irony in German often signals with:",opts:["a literal statement with exaggerated tone","very direct criticism","formal register","a subordinate clause"],a:0},{q:"'Das war wirklich eine Glanzleistung.' said after a failure uses:",opts:["hyperbole","understatement","verbal irony / sarcasm","a simile"],a:2},{q:"'So ein Zufall aber auch!' expresses:",opts:["genuine surprise","sarcastic disbelief","a formal conclusion","a rhetorical question"],a:1},{q:"Understatement (Untertreibung) is a form of:",opts:["hyperbole","irony","metaphor","alliteration"],a:1},{q:"Humour in language often depends on:",opts:["only grammar","shared context and timing","spelling","numbers"],a:1}],
[{q:"Efficient listening in a dense lecture involves:",opts:["transcribing everything","focusing on keywords and structure","avoiding making notes","only listening without pausing"],a:1},{q:"'im Umkehrschluss' means:",opts:["in addition to this","by contrast","by the reverse logic / conversely","in a broader sense"],a:2},{q:"'Die Befunde legen nahe, dass...' means:",opts:["The findings rule out that...","The findings suggest that...","The findings prove beyond doubt that...","The findings are unrelated to..."],a:1},{q:"'der Exkurs' in a lecture is:",opts:["the main point","a digression","the conclusion","a citation"],a:1},{q:"To follow a dense argument, identify the:",opts:["background noise","main thesis and supporting steps","speaker's clothes","room temperature"],a:1}],
[{q:"'der Sachverhalt' means:",opts:["the opinion","the state of affairs / the facts","the proposal","the law"],a:1},{q:"'subsidiaer' in political discourse means:",opts:["central","autonomous","at the lowest appropriate level","judicial"],a:2},{q:"A 'Weissbuch' in policy is:",opts:["a blank document","an official government policy paper","a secret report","an informal memo"],a:1},{q:"'der Gesetzentwurf' is:",opts:["a passed law","a draft bill","a court ruling","a petition"],a:1},{q:"Policy argument requires:",opts:["emotion only","evidence and clear reasoning","slogans","no structure"],a:1}],
[{q:"'Schadenfreude' in English is best:",opts:["translated word for word","kept as a loanword (no direct equivalent)","replaced with 'happiness'","avoided entirely"],a:1},{q:"'Uebersetzen' differs from 'Dolmetschen' in:",opts:["language pair","written vs. spoken","formality","technical vocabulary"],a:1},{q:"A 'skopos' in translation theory defines:",opts:["the source text style","the target text purpose and audience","the translator's credentials","the payment structure"],a:1},{q:"'Fernweh' is best rendered by:",opts:["a single English word","explanation or a borrowing","'fear'","'tired'"],a:1},{q:"A faithful translation preserves:",opts:["only the words","meaning, tone and intent","only the length","only the grammar"],a:1}],
[{q:"'Das Niveau des Textes halten' in editing means:",opts:["lowering the register","keeping the register and tone consistent","adding footnotes","translating for clarity"],a:1},{q:"In a masterclass critique, you address:",opts:["only weaknesses","only word choices","structure, argument, style, and language together","length only"],a:2},{q:"'metatextuell' refers to:",opts:["text about the content itself","text that is very long","text about other texts or writing processes","text with many footnotes"],a:2},{q:"A masterclass editor balances:",opts:["speed over quality","correction with the author's voice","only grammar","only style"],a:1},{q:"The final editing pass focuses on:",opts:["adding length","polishing consistency and nuance","changing the topic","removing all commas"],a:1}]
]
};
