const frModuleTheory = {
A1:[
{title:"Core Phrases & French Sounds",rules:["French nouns are masculine (le) or feminine (la); learn the article with each noun.","Accents change sound: e' (acute) = 'ay', e` (grave) = 'eh', e^ (circumflex) often historical.","Final consonants are usually silent, but 'liaison' links them to a following vowel.","Greetings depend on time: Bonjour (day), Bonsoir (evening), Salut (informal)."],examples:[{src:"Bonjour, comment vous appelez-vous?",tr:"Hello, what is your name?"},{src:"Je m'appelle Anna. Enchante.",tr:"My name is Anna. Nice to meet you."},{src:"C'est mon livre.",tr:"This is my book."}],keyPattern:"Subject + Verb + Rest: Je bois un cafe."},
{title:"Questions & Everyday Choices",rules:["Question words: qui (who), que/quoi (what), ou (where), quand (when), pourquoi (why), comment (how).","Three ways to ask yes/no: intonation, est-ce que..., or inversion (Parlez-vous...?).","Numbers 70-99 combine: soixante-dix (70), quatre-vingts (80), quatre-vingt-dix (90).","Order politely with 'Je voudrais...' + noun."],examples:[{src:"Ou habitez-vous?",tr:"Where do you live?"},{src:"Combien ca coute?",tr:"How much is that?"},{src:"Je voudrais un cafe, s'il vous plait.",tr:"I would like a coffee, please."}],keyPattern:"Est-ce que + subject + verb? Est-ce que tu viens?"},
{title:"Articles & Sentence Order",rules:["Definite: le, la, l', les. Indefinite: un, une, des.","Regular -er verbs: je -e, tu -es, il/elle -e, nous -ons, vous -ez, ils/elles -ent.","Negation wraps the verb: ne ... pas (Je ne parle pas).","Adjectives usually follow the noun and agree in gender and number."],examples:[{src:"Je vois le chien.",tr:"I see the dog."},{src:"Nous apprenons le francais.",tr:"We are learning French."},{src:"Ce n'est pas un probleme.",tr:"That is not a problem."}],keyPattern:"Subject + ne + verb + pas: Je ne comprends pas."},
{title:"Reading, Listening & Context",rules:["Cognates aid reading: table/table, animal/animal, nation/nation.","Watch elision: le + ami = l'ami; je + ai = j'ai.","Listen for the verb right after the subject to find the action.","Time words often open the sentence: Aujourd'hui, je travaille."],examples:[{src:"Aujourd'hui, je lis un livre.",tr:"Today I am reading a book."},{src:"La pomme est rouge.",tr:"The apple is red."},{src:"Nous allons au cinema.",tr:"We are going to the cinema."}],keyPattern:"Time + Subject + Verb: Demain, je visite Paris."},
{title:"Speaking, Writing & Review",rules:["Join ideas with et (and), mais (but), ou (or).","'aimer' + infinitive expresses liking: J'aime danser.","Build a self-introduction: name, origin, age, languages.","Contractions: a + le = au, de + le = du, a + les = aux."],examples:[{src:"Je viens d'Espagne et j'apprends le francais.",tr:"I come from Spain and I am learning French."},{src:"J'aime jouer au football.",tr:"I like playing football."},{src:"Je m'appelle Tom. J'ai vingt ans.",tr:"My name is Tom. I am twenty."}],keyPattern:"Idea 1 + et/mais/ou + Idea 2: Je lis et j'ecris."}
],
A2:[
{title:"Talking About the Past (Passe compose)",rules:["Passe compose = avoir/etre (present) + past participle.","Most verbs use avoir; 17 'DR MRS VANDERTRAMP' verbs of movement use etre.","With etre, the participle agrees with the subject (elle est allee).","Regular participles: -er -> -e, -ir -> -i, -re -> -u."],examples:[{src:"J'ai vu un film.",tr:"I watched a film."},{src:"Nous sommes alles a Paris.",tr:"We went to Paris."},{src:"Elle a bu un cafe.",tr:"She drank a coffee."}],keyPattern:"Subject + avoir/etre + participle: J'ai mange."},
{title:"Getting Around & Asking Directions",rules:["Directions: tout droit (straight), a gauche (left), a droite (right), retour (back).","Use 'a' + place: a la gare, au marche, aux toilettes.","Ordinals for streets: la premiere/deuxieme/troisieme rue.","Location prepositions: a cote de, en face de, pres de, entre."],examples:[{src:"Allez tout droit puis a gauche.",tr:"Go straight ahead then left."},{src:"Comment aller au marche?",tr:"How do I get to the market?"},{src:"La banque est a cote de la pharmacie.",tr:"The bank is next to the pharmacy."}],keyPattern:"Comment aller a/au/a la + place?"},
{title:"Reflexive & Modal Expressions",rules:["Reflexive verbs use me/te/se/nous/vous/se before the verb: je me leve.","In passe compose reflexives take etre and agree: elle s'est levee.","Express ability/obligation with pouvoir, devoir, vouloir + infinitive.","'il faut' + infinitive means 'one must / it is necessary to'."],examples:[{src:"Je me leve a sept heures.",tr:"I get up at seven."},{src:"Tu ne peux pas fumer ici.",tr:"You cannot smoke here."},{src:"Il faut partir maintenant.",tr:"We must leave now."}],keyPattern:"Subject + reflexive pronoun + verb: Je me reveille."},
{title:"Stories, Weather & Context",rules:["Weather uses 'il': Il pleut, il neige, il fait beau/froid.","Imparfait describes background and habits in the past: je jouais.","Sequencing: d'abord, ensuite, puis, enfin.","Choose passe compose (single events) vs imparfait (description/habit)."],examples:[{src:"Hier, il faisait beau.",tr:"Yesterday the weather was nice."},{src:"D'abord j'ai mange, ensuite je suis parti.",tr:"First I ate, then I left."},{src:"Il fait froid et il y a du vent.",tr:"It is cold and windy."}],keyPattern:"D'abord... ensuite... puis... enfin..."},
{title:"Emails, Travel & Review",rules:["Informal email: 'Salut...' / 'Bonjour...'; close 'A bientot' or 'Bises'.","Formal email: 'Madame, Monsieur,'; close 'Cordialement' or 'Veuillez agreer...'","Polite requests: 'Pourriez-vous...' / 'Je vous serais reconnaissant de...'","Travel basics: le billet (ticket), le quai (platform), changer (to change)."],examples:[{src:"Madame, Monsieur, je vous ecris au sujet de...",tr:"Dear Sir or Madam, I am writing regarding..."},{src:"Un aller simple pour Lyon, s'il vous plait.",tr:"A one-way ticket to Lyon, please."},{src:"Cordialement, Marie.",tr:"Kind regards, Marie."}],keyPattern:"Madame, Monsieur, + body + Cordialement."}
],
B1:[
{title:"Expressing Opinions",rules:["Opinion starters: A mon avis, Je pense que, Je trouve que, Il me semble que...","Some opinion verbs in the negative trigger the subjunctive (Je ne pense pas que ce soit...).","Agree/disagree: Je suis d'accord / Je ne suis pas d'accord.","Give reasons with parce que / car."],examples:[{src:"A mon avis, c'est important.",tr:"In my opinion, it is important."},{src:"Je trouve que nous devrions pratiquer plus.",tr:"I think we should practise more."},{src:"Je ne suis pas d'accord car c'est trop cher.",tr:"I disagree because it is too expensive."}],keyPattern:"Je pense que + indicative: Je pense qu'il a raison."},
{title:"Subordinate Clauses",rules:["Conjunctions like bien que, pour que, avant que trigger the subjunctive.","quand/lorsque (when), pendant que (while), des que (as soon as).","'si' clauses: si + present -> future; si + imparfait -> conditionnel.","Relative pronouns: qui (subject), que (object), ou (place/time), dont (of which)."],examples:[{src:"Bien qu'il pleuve, nous sortons.",tr:"Although it is raining, we are going out."},{src:"Je reste chez moi parce que je suis malade.",tr:"I am staying home because I am ill."},{src:"Si j'avais le temps, je voyagerais.",tr:"If I had time, I would travel."}],keyPattern:"Bien que + subjunctive: Bien que ce soit difficile."},
{title:"Work, Media & Reported Speech",rules:["Workplace vocabulary: la candidature, le CV, le salaire, la reunion.","Reported speech shifts tense: present -> imparfait, futur -> conditionnel.","Passive (etre + participle) is common in formal and media texts.","Connectors of consequence: donc, par consequent, c'est pourquoi."],examples:[{src:"Il a dit qu'il etait fatigue.",tr:"He said he was tired."},{src:"Le produit est fabrique en France.",tr:"The product is made in France."},{src:"Je suis malade, donc je reste a la maison.",tr:"I am ill, so I am staying home."}],keyPattern:"Il dit qu'il + verb; reported: Il a dit qu'il etait..."},
{title:"Advice, Plans & Problem Solving",rules:["Give advice with the conditional: Tu devrais dormir plus.","Future: futur proche (aller + infinitive) or futur simple.","Express intentions: avoir l'intention de, projeter de.","Polite suggestions: Nous pourrions..., Et si on...?"],examples:[{src:"Tu devrais voir un medecin.",tr:"You should see a doctor."},{src:"L'annee prochaine, je vais demenager a Vienne.",tr:"Next year I am going to move to Vienna."},{src:"Et si on prenait un cafe?",tr:"How about a coffee?"}],keyPattern:"Tu devrais + infinitive: Tu devrais pratiquer."},
{title:"Essays, Interviews & Review",rules:["Structure: introduction, developpement, conclusion.","Balance ideas with d'une part... d'autre part...","Conclude with En somme / Pour conclure / En conclusion.","In interviews, present points forts (strengths) and points faibles (weaknesses)."],examples:[{src:"D'une part c'est cher, d'autre part c'est utile.",tr:"On one hand it is expensive, on the other it is useful."},{src:"En somme, on peut dire que...",tr:"In short, one can say that..."},{src:"Mon point fort, c'est le travail d'equipe.",tr:"My strength is teamwork."}],keyPattern:"D'une part..., d'autre part...; En conclusion..."}
],
B2:[
{title:"Debate & Argumentation",rules:["Concede then counter: Certes..., mais...; Il est vrai que..., toutefois...","Soften disagreement: Je comprends votre point, cependant...","Strong claims: Il est indeniable que...","Add weight: de plus, en outre, par ailleurs."],examples:[{src:"Certes, c'est cher, mais cela en vaut la peine.",tr:"Admittedly it is expensive, but it is worth it."},{src:"Il est indeniable que nous devons agir.",tr:"It is undeniable that we must act."},{src:"Je comprends votre point, cependant je nuancerais.",tr:"I understand your point, however I would qualify it."}],keyPattern:"Certes + statement, mais + counterpoint."},
{title:"Passive Voice & Register",rules:["Passive: etre + past participle, agent introduced by 'par': Le texte est lu par tous.","'on' is a frequent active alternative to the passive: On dit que...","Pronominal passive: Ce produit se vend bien.","Choose register: obtenir (formal) vs avoir; s'exprimer formally vs casually."],examples:[{src:"Le projet a ete finance par l'Etat.",tr:"The project was financed by the State."},{src:"On parle francais ici.",tr:"French is spoken here."},{src:"Ce livre se lit facilement.",tr:"This book reads easily."}],keyPattern:"Object + etre + participle + par + agent."},
{title:"Complex Connectors & Structure",rules:["Two-part connectors: non seulement... mais aussi...; soit... soit...","'plus... plus...' / 'moins... moins...' express proportion.","Contrast: alors que, tandis que, en revanche.","Nominalization adds formality: l'amelioration, le developpement."],examples:[{src:"Plus je pratique, mieux je parle.",tr:"The more I practise, the better I speak."},{src:"Elle parle non seulement francais mais aussi allemand.",tr:"She speaks not only French but also German."},{src:"Il travaille, alors qu'elle etudie.",tr:"He works, whereas she studies."}],keyPattern:"Plus + clause, plus + clause: Plus tot, mieux c'est."},
{title:"News Analysis & Abstract Ideas",rules:["Attribute sources: selon..., d'apres un rapport...","Abstract nouns from adjectives: libre -> liberte; durable -> durabilite.","Describe trends: la hausse, la baisse, le recul, l'evolution.","Separate fact (les faits) from opinion (le commentaire)."],examples:[{src:"Selon un rapport, le nombre augmente.",tr:"According to a report, the number is rising."},{src:"Le developpement durable joue un grand role.",tr:"Sustainable development plays a major role."},{src:"Il y a eu un net recul.",tr:"There was a clear decline."}],keyPattern:"Selon + source, + statement."},
{title:"Negotiation, Presentation & Review",rules:["Negotiation: Nous pourrions nous mettre d'accord sur...; a condition que + subjunctive.","Presentation signposts: Tout d'abord..., Ensuite..., Pour terminer...","Constructive feedback with conditional: pourrait etre mieux etaye.","Reference visuals: Comme le montre ce graphique..."],examples:[{src:"Nous pourrions trouver un compromis.",tr:"We could find a compromise."},{src:"Comme le montre ce graphique, le chiffre d'affaires augmente.",tr:"As this graph shows, revenue is rising."},{src:"L'argument pourrait etre mieux etaye.",tr:"The argument could be better supported."}],keyPattern:"Tout d'abord..., ensuite..., pour terminer..."}
],
C1:[
{title:"Nuance & Subtle Meaning",rules:["Qualifiers fine-tune meaning: a peine (hardly), plutot (rather), quasiment (almost).","'certes... mais...' and 'd'une certaine maniere' add nuance.","Mood choice (indicative vs subjunctive) shifts certainty.","Word order and stress (c'est... que) highlight elements."],examples:[{src:"C'est tout a fait possible.",tr:"That is entirely possible."},{src:"Il a, dans une certaine mesure, raison.",tr:"He is right, to a certain extent."},{src:"C'est lui qui a decide.",tr:"It is he who decided."}],keyPattern:"Mise en relief: C'est ... que ... (C'est ici que tout commence)."},
{title:"Academic Reading & Precision",rules:["Academic framing: La presente etude montre...; Au coeur du texte se trouve...","Use precise connectors: en effet, or, ainsi, des lors.","Cite with notes de bas de page and clear references.","Subjunctive after expressions of necessity, doubt, emotion."],examples:[{src:"En raison des resultats, nous concluons que...",tr:"Owing to the results, we conclude that..."},{src:"La presente etude examine l'influence de...",tr:"The present study examines the influence of..."},{src:"Il faut que cela soit clair.",tr:"It must be clear."}],keyPattern:"En raison de / du fait de + noun: en raison du climat."},
{title:"Idioms & Stylistic Choice",rules:["Idioms carry culture: 'ce n'est pas la mer a boire' = it is not that hard.","'avoir le cafard' = to feel down; 'poser un lapin' = to stand someone up.","Match idiom register to context - avoid argot in formal writing.","Parataxe (short clauses) vs hypotaxe (subordination) shapes rhythm."],examples:[{src:"Ce n'est pas la mer a boire.",tr:"It is not such a big deal."},{src:"Il m'a pose un lapin.",tr:"He stood me up."},{src:"J'ai le cafard aujourd'hui.",tr:"I feel down today."}],keyPattern:"Fixed idiom, used whole: coûter les yeux de la tete."},
{title:"Long-form Listening & Summary",rules:["Follow the 'fil conducteur' (main thread) of a long talk.","Recognize discourse markers: d'une part, par consequent, en definitive.","Plus-que-parfait marks an event before another past event.","A 'compte rendu' reports neutrally, without personal evaluation."],examples:[{src:"Apres qu'il eut parle, on posa des questions.",tr:"After he had spoken, questions were asked."},{src:"L'auteur soutient que...",tr:"The author argues that..."},{src:"Par consequent, une nouvelle image se dessine.",tr:"Consequently, a new picture emerges."}],keyPattern:"Apres que / quand + plus-que-parfait, ... passe."},
{title:"Formal Writing, Speaking & Editing",rules:["Formal letters open 'Madame, Monsieur,' and close 'Veuillez agreer, Madame, Monsieur, mes salutations distinguees.'","Use 'ci-joint' / 'veuillez trouver ci-joint' for attachments.","In speech, hedge with 'pour ainsi dire', 'en quelque sorte', 'grosso modo'.","Edit out fillers (en fait, du coup) and heavy nominalizations."],examples:[{src:"Veuillez trouver ci-joint les documents.",tr:"Please find the documents attached."},{src:"Grosso modo, il s'agit de trois points.",tr:"Roughly speaking, it is about three points."},{src:"Veuillez agreer mes salutations distinguees.",tr:"Yours faithfully."}],keyPattern:"Madame, Monsieur, + body + Veuillez agreer..."}
],
C2:[
{title:"Near-native Tone & Flexibility",rules:["Spoken French drops 'ne' and uses on for nous: On y va.","Native rhythm uses 'mise en relief' and topic-fronting naturally.","Discourse particles: quoi, bon, enfin, donc add idiomatic colour.","Read pragmatics: irony, politeness, social distance."],examples:[{src:"De toute facon, je voulais le dire.",tr:"In any case, I wanted to say it."},{src:"C'est exactement ce que je veux dire.",tr:"That is exactly what I mean."},{src:"Ce n'est pas du tout mon propos.",tr:"That is not at all my point."}],keyPattern:"Topic + reprise pronoun: Moi, ce livre, je l'adore."},
{title:"Regional Varieties",rules:["Standard French is the reference; varieties differ in accent and lexis.","Quebec: 'icitte' (ici), 'char' (voiture); Belgium: 'septante' (70), 'nonante' (90).","Recognize but do not necessarily reproduce strong regionalisms.","Southern French pronounces more final 'e' and nasal vowels differently."],examples:[{src:"Septante (Belgique) = soixante-dix.",tr:"Seventy (Belgian usage)."},{src:"Un char (Quebec) = une voiture.",tr:"A car (Quebec usage)."},{src:"C'est du francais standard.",tr:"That is standard French."}],keyPattern:"Regional lexis marks origin: septante / nonante (BE, CH)."},
{title:"Rhetorical Control",rules:["Gradation builds from weak to strong for impact.","Anaphore repeats an opening word across clauses.","Rhetorical questions steer the audience.","Parenthese inserts asides without breaking the main thread."],examples:[{src:"Nous sommes venus, nous avons vu, nous avons vaincu.",tr:"We came, we saw, we conquered."},{src:"Est-ce juste? Est-ce sage? Est-ce necessaire?",tr:"Is it fair? Is it wise? Is it necessary?"},{src:"Le resultat - et c'est decisif - convainc.",tr:"The result - and this is decisive - convinces."}],keyPattern:"Anaphora: repeat the opening word for rhythm."},
{title:"Literary Texture",rules:["Devices: metaphore, synesthesie, personnification, epithete transferee.","Enjambement carries a clause across a line break in poetry.","Register and lexical choice create atmosphere.","Read for subtext, connotation and irony."],examples:[{src:"Un bleu silencieux couvrait la vallee.",tr:"A silent blue covered the valley."},{src:"Le temps s'etirait lentement.",tr:"Time stretched out slowly."},{src:"Sa parole faisait loi.",tr:"His word was law."}],keyPattern:"Sensory transfer (synaesthesia): une couleur chaude."},
{title:"Specialized & Masterclass Tasks",rules:["Domain lexis: legal (le conseil juridique), economic (le PIB), academic (l'hypothese).","Translate untranslatables by explanation or loan: depaysement, flaner.","Distinguish traduire (written) from interpreter (spoken).","Editing at this level preserves register, intent and nuance together."],examples:[{src:"Le produit interieur brut augmente de deux pour cent.",tr:"The gross domestic product rises by two percent."},{src:"Le depaysement est difficile a traduire.",tr:"'Depaysement' is hard to translate."},{src:"L'etat des choses est juridiquement complexe.",tr:"The state of affairs is legally complex."}],keyPattern:"Precision lexis + preserved register across the whole text."}
]
};

const frBooks = [
{level:"A1",title:"Cours de francais (A1)",author:"TV5Monde / Apprendre",type:"Online course",desc:"Free interactive lessons and authentic video clips graded for absolute beginners."},
{level:"A1",title:"Alter Ego+ A1",author:"Hachette FLE",type:"Textbook",desc:"Popular communicative coursebook with audio, clear grammar and everyday situations."},
{level:"A1",title:"Petites histoires faciles",author:"Olly Richards (Short Stories)",type:"Graded reader",desc:"Very simple illustrated stories with glossaries, designed for first reading in French."},
{level:"A2",title:"Alter Ego+ A2",author:"Hachette FLE",type:"Textbook",desc:"Continues the method with the past tenses, travel and daily-life communication."},
{level:"A2",title:"Le Petit Nicolas",author:"Sempe & Goscinny",type:"Graded reader",desc:"Charming, simple childhood stories - a classic, accessible step into reading French."},
{level:"A2",title:"Grammaire progressive du francais (debutant)",author:"CLE International",type:"Grammar workbook",desc:"Theory on the left page, exercises on the right - excellent for self-study."},
{level:"B1",title:"Edito B1",author:"Didier FLE",type:"Textbook",desc:"Theme-based course with authentic documents bridging toward independent use."},
{level:"B1",title:"L'Etranger",author:"Albert Camus",type:"Novel",desc:"Short, clear prose - a strong first 'real' French novel for upper-B1 readers."},
{level:"B1",title:"Grammaire progressive du francais (intermediaire)",author:"CLE International",type:"Grammar workbook",desc:"Consolidates tenses, pronouns and connectors with plenty of practice."},
{level:"B2",title:"Edito B2",author:"Didier FLE",type:"Textbook",desc:"Advanced course with debate, register and argumentative writing tasks."},
{level:"B2",title:"No et moi",author:"Delphine de Vigan",type:"Novel",desc:"Contemporary, emotionally engaging novel in accessible modern French."},
{level:"B2",title:"Le Bon Usage (selections)",author:"Grevisse & Goosse",type:"Reference grammar",desc:"The authoritative reference to consult for finer grammatical points."},
{level:"C1",title:"Edito C1",author:"Didier FLE",type:"Textbook",desc:"Demanding C1 course with sophisticated texts, idioms and precise grammar work."},
{level:"C1",title:"La Peste",author:"Albert Camus",type:"Literature",desc:"Rich but readable novel for analysing style, nuance and argument."},
{level:"C1",title:"Le Francais correct",author:"Maurice Grevisse",type:"Usage guide",desc:"Practical guide to common difficulties that sharpens register and accuracy."},
{level:"C2",title:"Cosmopolite C1/C2",author:"Hachette FLE",type:"Textbook",desc:"Top-level course preparing near-native command across academic and professional registers."},
{level:"C2",title:"A la recherche du temps perdu (extraits)",author:"Marcel Proust",type:"Literature",desc:"Stylistically demanding masterwork for mastering literary texture and long syntax."},
{level:"C2",title:"Le Bon Usage",author:"Grevisse & Goosse",type:"Reference",desc:"Comprehensive reference grammar for truly native-like precision and nuance."}
];
