const frTaskQBank = {
A1:[
[{q:"What does 'Bonjour' mean?",opts:["Good evening","Good night","Hello / Good day","Goodbye"],a:2},{q:"Which greeting is used in the evening?",opts:["Bonjour","Salut","Bonsoir","Au revoir"],a:2},{q:"'Enchante(e)' means:",opts:["Thank you","Nice to meet you","Excuse me","Please"],a:1},{q:"'Salut' is used in ___ situations.",opts:["formal","informal","written-only","ceremonial"],a:1},{q:"'Comment vous appelez-vous?' asks:",opts:["How are you?","What is your name?","Where do you live?","How old are you?"],a:1}],
[{q:"Which accent makes 'e' sound like 'ay'?",opts:["e grave (e`)","e acute (e')","e circumflex (e^)","cedilla (c,)"],a:1},{q:"The letter 'c' before 'e' or 'i' sounds like:",opts:["k","g","s","zh"],a:2},{q:"'liaison' in French means:",opts:["a silent final consonant","linking a final consonant to a vowel-starting word","dropping an e","an accent mark"],a:1},{q:"The cedilla (c,) makes 'c' sound like:",opts:["k","s","sh","g"],a:1},{q:"Final consonants in French are usually:",opts:["stressed","silent","doubled","rolled"],a:1}],
[{q:"What is 'vingt' in English?",opts:["12","20","22","80"],a:1},{q:"How do you say 70 in French?",opts:["septante","soixante-dix","setante","sept-dix"],a:1},{q:"Which is correct for 80?",opts:["huitante","quatre-vingts","octante","huit-vingt"],a:1},{q:"'cent' means:",opts:["10","100","1000","11"],a:1},{q:"'quinze' is:",opts:["5","50","15","55"],a:2}],
[{q:"Which article goes with 'table' (feminine)?",opts:["le","la","les","un"],a:1},{q:"Which article goes with 'livre' (book, masculine)?",opts:["le","la","les","une"],a:0},{q:"The plural article for all genders is:",opts:["le","la","l'","les"],a:3},{q:"Indefinite article for a feminine noun:",opts:["un","une","des","le"],a:1},{q:"Before a vowel, 'le'/'la' become:",opts:["les","l'","un","de"],a:1}],
[{q:"Correct form: 'Tu ___ en France.'",opts:["habite","habites","habitez","habitons"],a:1},{q:"Which ending for 'nous' with -er verbs?",opts:["-e","-es","-ons","-ez"],a:2},{q:"Conjugate 'avoir' for 'elle':",opts:["ai","as","a","avons"],a:2},{q:"'je ___' (etre):",opts:["es","suis","est","sommes"],a:1},{q:"'vous ___ francais' (parler):",opts:["parlez","parles","parle","parlent"],a:0}],
[{q:"How do you politely order in French?",opts:["Je veux un cafe","Je voudrais un cafe, s'il vous plait","Donne-moi un cafe","Apporte le cafe"],a:1},{q:"'L'addition, s'il vous plait' means:",opts:["The menu please","Can I order?","The bill please","Excuse me"],a:2},{q:"'Qu'est-ce que vous recommandez?' means:",opts:["What is the special?","What do you recommend?","Do you have a table?","Is service included?"],a:1},{q:"'la carte' is the:",opts:["bill","menu","waiter","kitchen"],a:1},{q:"'Bon appetit!' means:",opts:["Cheers!","Enjoy your meal!","The bill, please!","Welcome!"],a:1}],
[{q:"'la soeur' means:",opts:["brother","mother","sister","aunt"],a:2},{q:"'le grand-pere' means:",opts:["uncle","grandfather","father","stepfather"],a:1},{q:"French for 'cousin' (female)?",opts:["la cousine","la soeur","la niece","la tante"],a:0},{q:"'les parents' means:",opts:["the children","the parents","the grandparents","the cousins"],a:1},{q:"'le fils' means:",opts:["son","daughter","nephew","brother"],a:0}],
[{q:"'se lever' means:",opts:["to eat","to sleep","to get up","to go out"],a:2},{q:"'prendre le petit-dejeuner' means:",opts:["to shower","to have breakfast","to drive","to work"],a:1},{q:"'s'endormir' means:",opts:["to wake up","to dream","to fall asleep","to rest"],a:2},{q:"'travailler' means:",opts:["to play","to work","to wait","to walk"],a:1},{q:"'rentrer a la maison' means:",opts:["to go shopping","to go home","to go out","to go to work"],a:1}],
[{q:"'Ou habitez-vous?' asks about:",opts:["your name","where you live","your age","what you do"],a:1},{q:"Which word asks 'why'?",opts:["qui","quoi","pourquoi","quand"],a:2},{q:"'Combien ca coute?' means:",opts:["What time is it?","How much does it cost?","Where is it?","Is it open?"],a:1},{q:"'Qui est-ce?' asks:",opts:["What is that?","Where is that?","Who is it?","When is it?"],a:2},{q:"To ask someone's name formally:",opts:["Comment tu t'appelles?","Comment vous appelez-vous?","Qui es-tu?","Que fais-tu?"],a:1}],
[{q:"After 'Comment allez-vous?' a polite response is:",opts:["Je ne sais pas","Tres bien, merci. Et vous?","Non","Parlez-vous anglais?"],a:1},{q:"'Pouvez-vous repeter, s'il vous plait?' means:",opts:["Can you help me?","Can you repeat that please?","Can you speak slower?","Where is the exit?"],a:1},{q:"Which farewell is most formal?",opts:["Salut","Ciao","Au revoir","A tout a l'heure"],a:2},{q:"'Excusez-moi, ou est...?' begins a:",opts:["complaint","polite request for directions","greeting","goodbye"],a:1},{q:"'A demain!' means:",opts:["See you tomorrow!","Good morning!","Until later!","Goodbye forever!"],a:0}]
],
A2:[
[{q:"Which auxiliary is used for 'aller' in passe compose?",opts:["avoir","etre","faire","aller"],a:1},{q:"Correct passe compose of 'manger'?",opts:["j'ai mange","j'ai mangi","je suis mange","j'ai manges"],a:0},{q:"'Hier, je ___ au cinema.'",opts:["ai alle","suis alle","allais","irai"],a:1},{q:"Past participle of 'finir':",opts:["fini","finu","finit","finer"],a:0},{q:"'J'ai ___ le francais.' (etudier)",opts:["etudie","etudier","etudiais","etudions"],a:0}],
[{q:"'Tout droit' means:",opts:["turn left","straight ahead","turn right","go back"],a:1},{q:"'Prenez la premiere rue a gauche' means:",opts:["take the second street right","take the first street on the left","go straight","take the next corner"],a:1},{q:"'Comment est-ce que je peux aller a la gare?' means:",opts:["Is the station far?","How do I get to the station?","Where is the bus stop?","How long does it take?"],a:1},{q:"'tournez a droite' means:",opts:["turn left","turn right","go straight","stop"],a:1},{q:"'en face de' means:",opts:["next to","opposite","behind","far from"],a:1}],
[{q:"'C'est trop cher pour moi' means:",opts:["I'll take it","That's too expensive for me","Do you have another size?","It fits perfectly"],a:1},{q:"'Vous l'avez en taille M?' means:",opts:["Do you have the receipt?","Where is the changing room?","Do you have this in size M?","Can I pay by card?"],a:2},{q:"'Je regarde seulement' means:",opts:["I'll buy two","I'm just looking","Can you help me?","I'd like to return this"],a:1},{q:"'en solde' means:",opts:["sold out","on sale","too expensive","second-hand"],a:1},{q:"'Je peux payer par carte?' asks about:",opts:["cash only","paying by card","a discount","the receipt"],a:1}],
[{q:"Which verb is reflexive?",opts:["manger","dormir","se lever","venir"],a:2},{q:"Correct form: 'Elle ___ tous les matins.'(se reveiller)",opts:["se reveille","reveille","se reveillez","reveillez"],a:0},{q:"Where does the reflexive pronoun go?",opts:["after the verb","before the verb","at end of sentence","after subject"],a:1},{q:"In passe compose, reflexive verbs use:",opts:["avoir","etre","faire","aller"],a:1},{q:"'se laver' means:",opts:["to wash oneself","to walk","to eat","to sleep"],a:0}],
[{q:"'Je dois partir maintenant.' The infinitive goes:",opts:["to position 1","after the modal verb","at end","before je"],a:1},{q:"Which modal expresses ability?",opts:["devoir","vouloir","pouvoir","savoir"],a:2},{q:"Correct: 'Tu ne ___ pas fumer ici.'",opts:["peux","dois","veux","sais"],a:0},{q:"'il faut' + infinitive expresses:",opts:["ability","necessity","permission","desire"],a:1},{q:"'Je ___ un cafe.' (want)",opts:["veux","dois","peux","sais"],a:0}],
[{q:"'Vous etes libre mardi?' means:",opts:["Is Tuesday good for you?","What time Tuesday?","Is Tuesday a holiday?","When is Tuesday?"],a:0},{q:"'Le rendez-vous est a midi et demi.' means:",opts:["at 12:00","at 12:30","at 1:30","at half past noon"],a:1},{q:"'Je dois malheureusement annuler' means:",opts:["I need to reschedule","I unfortunately have to cancel","I'm running late","I'll be there early"],a:1},{q:"'Ca vous convient a 10 heures?' asks if:",opts:["10 o'clock suits you","it is 10 o'clock","you are late","the meeting ended"],a:0},{q:"'prendre rendez-vous' means:",opts:["to cancel","to make an appointment","to be late","to arrive early"],a:1}],
[{q:"'Il pleut' means:",opts:["It's snowing","It's sunny","It's raining","It's cloudy"],a:2},{q:"'nuageux' means:",opts:["windy","sunny","foggy","cloudy"],a:3},{q:"'Quel temps fera-t-il demain?' means:",opts:["What is the weather now?","What will the weather be tomorrow?","Is it cold today?","What is the forecast?"],a:1},{q:"'Il fait chaud' means:",opts:["It's cold","It's hot","It's wet","It's windy"],a:1},{q:"'la neige' means:",opts:["rain","snow","sun","wind"],a:1}],
[{q:"'Veuillez agreer...' is used:",opts:["at the start of a formal email","at the end of a formal email","in informal messages","in spoken farewells"],a:1},{q:"'Madame, Monsieur' translates as:",opts:["Hi everyone","Dear Sir or Madam","Hello friends","Dear colleagues"],a:1},{q:"'Je me refere a votre email du...' means:",opts:["I am replying immediately","I refer to your email of...","I am forwarding your message","I have not received your email"],a:1},{q:"An informal email might open with:",opts:["Madame, Monsieur","Salut Tom,","Veuillez agreer","Cordialement"],a:1},{q:"'Veuillez trouver ci-joint...' means:",opts:["Please find attached...","I am writing because...","Best regards...","See you soon..."],a:0}],
[{q:"'Ou est le distributeur automatique le plus proche?' means:",opts:["Where is the nearest bus stop?","Where is the nearest ATM?","Where is the hotel?","Where is the nearest pharmacy?"],a:1},{q:"'Un aller simple pour Paris, s'il vous plait.' means:",opts:["One return to Paris","One one-way ticket to Paris, please","First class to Paris","One hotel room in Paris"],a:1},{q:"'Le train a du retard?' means:",opts:["Is the train fast?","Does the train have a dining car?","Is the train delayed?","Has the train departed?"],a:2},{q:"'changer de train' means:",opts:["to board","to change trains","to arrive","to buy a ticket"],a:1},{q:"'les bagages' means:",opts:["the ticket","the luggage","the platform","the seat"],a:1}],
[{q:"For retelling a story in written French, which tense is most common?",opts:["Passe compose","Present","Imparfait","Futur"],a:2},{q:"'Il raconta que...' introduces:",opts:["a question","indirect speech","a command","a comparison"],a:1},{q:"'Pour conclure' means:",opts:["At first","On the other hand","In the middle","In conclusion"],a:3},{q:"'D'abord... ensuite... puis...' are used to:",opts:["compare","sequence events","ask questions","negate"],a:1},{q:"'soudain' means:",opts:["slowly","suddenly","finally","never"],a:1}]
],
B1:[
[{q:"Which phrase introduces a personal opinion in French?",opts:["Il est connu que","A mon avis","Selon les statistiques","On dit que"],a:1},{q:"'Je suis d'avis que...' means:",opts:["It is said that...","It is a fact...","I am of the opinion that...","Studies show that..."],a:2},{q:"A more formal way to say 'I think' in French:",opts:["Je pense","Je crois","Il me semble que","Je trouve"],a:2},{q:"'Je (ne) suis (pas) d'accord' expresses:",opts:["a question","agreement/disagreement","a wish","a command"],a:1},{q:"'Je trouve que' is followed by which mood (affirmative)?",opts:["subjunctive","indicative","imperative","infinitive"],a:1}],
[{q:"In a 'parce que' clause, the verb goes:",opts:["to position 2","to the start","stays in normal position","to the end"],a:2},{q:"Which conjunction introduces a subordinate clause?",opts:["et","mais","car","bien que"],a:3},{q:"'bien que' requires which mood?",opts:["indicatif","conditionnel","subjonctif","infinitif"],a:2},{q:"'si' + present is followed by which tense for the result?",opts:["present/future","conditional","subjunctive","past"],a:0},{q:"Relative pronoun 'dont' replaces a phrase with:",opts:["a","de","pour","sur"],a:1}],
[{q:"'la candidature' means:",opts:["the salary","the job application","the promotion","the deadline"],a:1},{q:"'Je suis responsable du projet' means:",opts:["I am interested in the project","I am responsible for the project","I created the project","I finished the project"],a:1},{q:"'l'entretien d'embauche' is:",opts:["a pay raise","a resignation letter","a job interview","a work contract"],a:2},{q:"'le CV' is the:",opts:["cover letter","resume","contract","reference"],a:1},{q:"'faire des heures supplementaires' means:",opts:["to take a break","to work overtime","to quit","to be promoted"],a:1}],
[{q:"'le titre' (in a news context) means:",opts:["a documentary","a headline","an advertisement","an editorial"],a:1},{q:"'selon un rapport' means:",opts:["according to a report","before the report","despite the report","without a report"],a:0},{q:"Which verb signals reported information?",opts:["expliquer","entendre","rapporter","sentir"],a:2},{q:"'l'emission' means:",opts:["the newspaper","the TV/radio programme","the headline","the journalist"],a:1},{q:"While listening, the best strategy is to focus on:",opts:["every single word","key words and context","only the ending","the music"],a:1}],
[{q:"'Tu devrais dormir plus.' expresses:",opts:["a command","advice","a fact","a question"],a:1},{q:"'Je vous conseille de...' means:",opts:["I refuse to...","I demand that...","I would recommend...","I regret that..."],a:2},{q:"'A ta place, je...' means:",opts:["If I were you, I would...","You should never...","Instead of that...","On behalf of you..."],a:0},{q:"'devrais' is the ___ of devoir.",opts:["present","conditional","past","future"],a:1},{q:"'Il vaudrait mieux que...' means:",opts:["It is better that...","It would be better if...","It was better when...","It will never be better..."],a:1}],
[{q:"'Je voyagerai l'annee prochaine.' uses which tense?",opts:["Passe compose","Imparfait","Futur simple","Conditionnel"],a:2},{q:"'J'ai l'intention d'etudier.' means:",opts:["I used to study","I intend to study","I finished studying","I should study"],a:1},{q:"'prochainement' means:",opts:["recently","forever","soon","rarely"],a:2},{q:"Futur proche is formed with:",opts:["avoir + participle","aller + infinitive","etre + participle","modal + past"],a:1},{q:"'Je projette de partir' expresses:",opts:["a past event","a plan","a regret","a command"],a:1}],
[{q:"Indirect speech marker in French:",opts:["si","parce que","que","bien que"],a:2},{q:"'Il a dit qu'il ___ fatigue.'",opts:["est","etait","soit","serait"],a:1},{q:"'Elle a demande si je viendrais' uses which tense in the subordinate?",opts:["futur","conditionnel","subjonctif","imparfait"],a:1},{q:"Reported speech shifts present tense to:",opts:["future","imparfait","subjunctive","conditional"],a:1},{q:"'On dit que...' is a way to:",opts:["give an order","report general claims","express a wish","ask a question"],a:1}],
[{q:"'C'est du au fait que...' means:",opts:["It is unrelated to...","It follows that...","It is due to the fact that...","It is possible that..."],a:2},{q:"'trouver une solution' means:",opts:["to cause a problem","to find a solution","to avoid an issue","to discuss options"],a:1},{q:"'tout d'abord' means:",opts:["finally","in addition","first of all","however"],a:2},{q:"'Le probleme, c'est que...' introduces:",opts:["a solution","a statement of the problem","a greeting","a conclusion"],a:1},{q:"'parvenir a un compromis' means:",opts:["to start a fight","to reach a compromise","to give up","to win"],a:1}],
[{q:"A French essay typically opens with:",opts:["a personal anecdote","a thesis statement (these)","a dictionary definition","a list of examples"],a:1},{q:"'D'une part... d'autre part...' is used to:",opts:["list items","show contrast and balance","give examples","conclude"],a:1},{q:"'En somme' means:",opts:["To begin with...","By contrast...","In summary...","For example..."],a:2},{q:"The three parts of a dissertation are:",opts:["title, body, image","introduction, developpement, conclusion","intro, intro, intro","question, answer, question"],a:1},{q:"'par exemple' means:",opts:["in conclusion","for example","however","therefore"],a:1}],
[{q:"'Parlez-moi de vous.' means:",opts:["Where do you work?","Tell me about yourself.","What are your weaknesses?","Why do you want this job?"],a:1},{q:"'Mes points forts sont...' means:",opts:["My goals are...","My weaknesses are...","My strengths are...","My experience is..."],a:2},{q:"'Avez-vous des questions?' means:",opts:["Do you have references?","Are you available now?","Do you have any questions?","Can you start immediately?"],a:2},{q:"'Pourquoi postulez-vous?' asks:",opts:["When can you start?","Why are you applying?","What is your salary?","Where do you live?"],a:1},{q:"A good interview answer should be:",opts:["very long and vague","concrete with examples","one word only","off-topic"],a:1}]
],
B2:[
[{q:"'Il ne faut pas perdre de vue que...' means:",opts:["That cannot be denied","We must not lose sight of the fact that...","That should be avoided","That needs clarification"],a:1},{q:"To concede a point in French debate, use:",opts:["Certes, mais...","Non, jamais...","Absolument faux...","Comme je l'ai dit..."],a:0},{q:"'en definitive' means:",opts:["on the other hand","ultimately / in the final analysis","by contrast","in addition"],a:1},{q:"'Il est indeniable que...' means:",opts:["It is doubtful that...","It is undeniable that...","It is irrelevant that...","It is unclear that..."],a:1},{q:"'Je partage (ne partage pas) cet avis' expresses:",opts:["a greeting","(dis)agreement","a request","a summary"],a:1}],
[{q:"Correct passive in French:",opts:["Le texte est lu","Le texte lit","Le texte a lire","Tous lisent le texte etre"],a:0},{q:"'Le projet a ete finance par l'Etat.' uses:",opts:["actif","passif","pronominal","impersonnel"],a:1},{q:"'La decision sera annoncee demain.' indicates:",opts:["past action","a future passive","present state","a habitual action"],a:1},{q:"The passive agent is introduced by:",opts:["de/par","pour","sur","avec"],a:0},{q:"'On' as a subject is often used to avoid the:",opts:["future","passive","subjunctive","imperative"],a:1}],
[{q:"'non seulement... mais aussi...' means:",opts:["neither... nor...","not only... but also...","either... or...","if... then..."],a:1},{q:"'Plus tu pratiques, mieux tu parles.' shows:",opts:["contrast","proportion","concession","reason"],a:1},{q:"'alors que' is used to:",opts:["add information","show condition","express contrast / while","give examples"],a:2},{q:"'soit... soit...' means:",opts:["both... and...","either... or...","neither... nor...","not only..."],a:1},{q:"'tandis que' expresses:",opts:["cause","contrast/while","time only","condition"],a:1}],
[{q:"'selon les sources gouvernementales' means:",opts:["against government sources","according to government sources","beyond government statements","following government reports"],a:1},{q:"'le recul' means:",opts:["an increase","a recovery","a decline","an announcement"],a:2},{q:"'Les reactions ont ete mitigees.' means:",opts:["Reactions were positive","Reactions were negative","Reactions were mixed","There were no reactions"],a:2},{q:"'la hausse' means:",opts:["the rise","the fall","the report","the cause"],a:0},{q:"To distinguish fact from opinion, look for:",opts:["emotional adjectives vs. data","only the headline","the photo","the date"],a:0}],
[{q:"Which word is MOST formal?",opts:["avoir","beneficier","obtenir","prendre"],a:1},{q:"'par la presente' is used in:",opts:["casual conversation","formal documents","academic slang","media headlines"],a:1},{q:"'je t'envoie un msg' is:",opts:["formal","technical","colloquial","literary"],a:2},{q:"Register refers to the level of:",opts:["volume","formality","speed","accent"],a:1},{q:"'bouquin' (for book) belongs to ___ register.",opts:["very formal","colloquial","academic","legal"],a:1}],
[{q:"'Nous pourrions envisager un compromis.' means:",opts:["We reject the proposal","We could consider a compromise","We demand a different solution","We have no flexibility"],a:1},{q:"'c'est non-negociable' means:",opts:["that is negotiable","that is not negotiable","that depends","we can discuss this"],a:1},{q:"'sous reserve' means:",opts:["unconditionally","without notice","with reservation / conditionally","formally agreed"],a:2},{q:"'faire une proposition' means:",opts:["to reject an offer","to make a proposal","to sign a contract","to end talks"],a:1},{q:"'faire un compromis a mi-chemin' means:",opts:["to refuse","to meet halfway","to leave","to insist"],a:1}],
[{q:"Which is a nominalized infinitive?",opts:["le savoir","savoir","su","savait"],a:0},{q:"'le developpement durable' relates to:",opts:["innovation","sustainable development","productivity","efficiency"],a:1},{q:"Abstract noun from 'libre':",opts:["la liberte","la libre","le libre","la liberation"],a:0},{q:"Nominalizing the infinitive often takes the article:",opts:["la","le","les","une"],a:1},{q:"'la justice' is an abstract noun from:",opts:["juste","jour","jeu","joie"],a:0}],
[{q:"An argument needs a 'these' which is:",opts:["examples","counter-arguments","a clear main claim","a summary"],a:2},{q:"'L'argument central est que...' introduces:",opts:["a conclusion","a main claim/thesis","a supporting detail","a question"],a:1},{q:"'Pour etayer cette these...' means:",opts:["Against this idea...","The problem is...","To support this thesis...","Despite this..."],a:2},{q:"'En revanche, on peut objecter que...' introduces:",opts:["support","a counter-argument","an example","a conclusion"],a:1},{q:"A solid argument structure is:",opts:["claim - reason - example","example only","claim only","question - question"],a:0}],
[{q:"To signal end of a section in a presentation:",opts:["Pour resumer ce point...","Premierement...","Pour etre honnete...","Permettez-moi de commencer..."],a:0},{q:"'Comme vous pouvez le voir sur ce graphique...' means:",opts:["As the graph clearly shows...","As you can see from this graph...","The graph is missing data...","The graph contradicts this..."],a:1},{q:"A rhetorical question in a presentation is used to:",opts:["demand an answer","avoid the topic","engage the audience and signal a point","fill time"],a:2},{q:"'Permettez-moi d'expliquer brievement...' means:",opts:["Let me conclude...","Let me briefly explain...","Let me disagree...","Let me leave..."],a:1},{q:"Good presentation signposting helps the audience:",opts:["get confused","follow the structure","ignore the talk","leave early"],a:1}],
[{q:"'Je suggere de raccourcir ce paragraphe.' means:",opts:["I demand this section be removed","I suggest shortening this paragraph","This section is perfect","I disagree with this section"],a:1},{q:"'L'argument gagnerait a etre mieux etaye.' means:",opts:["The argument is wrong","The argument needs no evidence","The argument would benefit from better support","The argument is irrelevant"],a:2},{q:"Constructive feedback always includes:",opts:["only criticism","only praise","specific suggestions for improvement","personal opinions about the author"],a:2},{q:"'J'apprecie particulierement que...' is a way to:",opts:["criticise harshly","give positive feedback","end the talk","ask a question"],a:1},{q:"Good peer feedback is:",opts:["vague and general","specific and respectful","only negative","silent"],a:1}]
],
C1:[
[{q:"'a peine' is best translated as:",opts:["almost","hardly / barely","mostly","slightly"],a:1},{q:"'certes... mais...' expresses:",opts:["simple addition","concession + contrast","cause + effect","alternative"],a:1},{q:"'dans une certaine mesure' means:",opts:["without doubt","to some extent","in contrast","precisely"],a:1},{q:"'plutot' often signals:",opts:["a strong claim","a qualified/nuanced preference","a command","a negation"],a:1},{q:"'quasiment' means:",opts:["never","almost","hardly","loudly"],a:1}],
[{q:"'La problematique centrale est...' signals:",opts:["a methodological detail","the core issue of the text","a secondary argument","a conclusion"],a:1},{q:"A 'note de bas de page' is:",opts:["a heading","a footnote","a bibliography","an abstract"],a:1},{q:"'la presente etude montre' means:",opts:["The future study will show","The present study shows","The past study showed","The theoretical study predicts"],a:1},{q:"'exposer' in academic French means:",opts:["to hide","to set out / present","to ignore","to shorten"],a:1},{q:"Academic citations serve to:",opts:["fill space","support and attribute claims","add humour","confuse readers"],a:1}],
[{q:"'Ca ne casse pas trois pattes a un canard.' means:",opts:["It is dangerous","It's nothing special / not impressive","It is very fast","It has no legs"],a:1},{q:"'prendre quelqu'un pour un pigeon' means:",opts:["to be kind to someone","to take someone for a fool / cheat someone","to flatter someone","to ignore someone"],a:1},{q:"'avoir le cafard' means:",opts:["to have a headache","to be afraid of insects","to feel down / be depressed","to be very tired"],a:2},{q:"'tomber dans les pommes' means:",opts:["to faint","to fall asleep","to be late","to succeed"],a:0},{q:"Idiomatic register should match the:",opts:["weather","context and audience","time of day","sentence length"],a:1}],
[{q:"Using short, juxtaposed sentences in French creates:",opts:["ambiguity","a sense of speed and tension","academic tone","subordination"],a:1},{q:"Anaphore is the repetition of:",opts:["a word at the end of clauses","a word at the start of successive clauses","punctuation for emphasis","sentence length"],a:1},{q:"'Il fait nuit. Les rues sont vides. Personne ne parle.' uses:",opts:["hypotaxe","parataxe","chiasme","litote"],a:1},{q:"Hypotaxe is characterised by:",opts:["short equal clauses","subordinated, nested clauses","no verbs","only questions"],a:1},{q:"A long, subordinated sentence tends to feel more:",opts:["urgent","formal/reflective","casual","childish"],a:1}],
[{q:"'parmi' requires which case in French?",opts:["a subjunctive","nothing special - just a noun/pronoun","the conditional","the perfect infinitive"],a:1},{q:"'en depit de' takes:",opts:["an indicative verb","a noun or pronoun","a subjunctive","an infinitive"],a:1},{q:"'Quand il arriva, elle avait deja mange.' The past-before-past uses:",opts:["Imparfait","Passe compose","Plus-que-parfait","Futur anterieur"],a:2},{q:"The subjunctive follows expressions of:",opts:["certainty","doubt/necessity/emotion","fact","habit"],a:1},{q:"Plus-que-parfait is formed with:",opts:["aller + infinitive","avoir/etre (imparfait) + participle","avoir + infinitive","etre + infinitive"],a:1}],
[{q:"'le fil conducteur' of a lecture means:",opts:["a quotation","an error","the central thread / main argument","a transition"],a:2},{q:"An effective note-taking strategy is:",opts:["writing every word","paraphrasing key ideas","recording only numbers","sketching pictures only"],a:1},{q:"To verify comprehension of a complex passage, you should:",opts:["read a translation","summarize main points in your own words","avoid re-reading","underline every sentence"],a:1},{q:"'l'idee maitresse' is:",opts:["a minor detail","the core idea","the introduction","the footnote"],a:1},{q:"Connectors in a lecture (donc, ainsi) signal:",opts:["the end of attention","logical structure","background noise","unrelated topics"],a:1}],
[{q:"A compte rendu should:",opts:["include the author's personal opinion","include your personal evaluation","present the text's main ideas neutrally","expand the original argument"],a:2},{q:"'L'auteur soutient que...' signals:",opts:["a direct quote","attributed reported speech","your personal view","a counterargument"],a:1},{q:"The most common tense in academic French summaries is:",opts:["Imparfait","Present","Futur","Plus-que-parfait"],a:1},{q:"A critical summary adds, beyond a neutral one:",opts:["more plot","a reasoned evaluation","fictional details","longer quotes"],a:1},{q:"'selon l'auteur' means:",opts:["against the author","according to the author","without the author","despite the author"],a:1}],
[{q:"In a formal French letter, after 'Madame, Monsieur' comes:",opts:["a comma then uppercase","a comma then lowercase","a period / no punctuation (on new line)","an exclamation mark"],a:2},{q:"'Veuillez trouver ci-joint...' means:",opts:["I am requesting...","Please find attached...","I am responding to...","I am unable to send..."],a:1},{q:"'je t'envoie ca' vs 'je vous fais parvenir ce document' differs in:",opts:["tense","subject","formality","content"],a:2},{q:"'Veuillez agreer mes salutations distinguees' is:",opts:["very informal","a very formal closing","a greeting","a question"],a:1},{q:"Formal writing prefers:",opts:["slang","precise, neutral vocabulary","emojis","abbreviations"],a:1}],
[{q:"A filler phrase to gain thinking time in French:",opts:["Absolument pas","Eh bien, disons que...","Non","Oubliez ca"],a:1},{q:"'Pour ainsi dire' means:",opts:["in detail","so to speak / roughly","to put it bluntly","according to studies"],a:1},{q:"Hedging language in spoken French signals:",opts:["absolute certainty","full commitment","uncertainty or caution","avoidance of verbs"],a:2},{q:"'en quelque sorte' means:",opts:["in a way / so to speak","never","exactly","loudly"],a:0},{q:"Spontaneous speech uses ___ more than writing.",opts:["footnotes","fillers and self-corrections","passive voice","citations"],a:1}],
[{q:"A 'cheville' (filler word) that should often be cut:",opts:["parce que","franchement","afin que","bien que"],a:1},{q:"Passive constructions in heavy French prose should often be replaced with:",opts:["more passive","active voice","nominalized phrases","longer sentences"],a:1},{q:"'plethorique' in editing describes:",opts:["a very short text","an overly long, excessive text","a well-balanced text","a technical text"],a:1},{q:"Good editing improves:",opts:["only length","clarity and concision","the font","the colour"],a:1},{q:"Replacing a heavy noun phrase with a verb usually makes text:",opts:["heavier","livelier and clearer","longer","incorrect"],a:1}]
],
C2:[
[{q:"Which word order sounds most authentically native?",opts:["Je vais chez moi maintenant","Maintenant je rentre","Je maintenant vais chez moi","Vais-je chez moi"],a:1},{q:"'Ca se voit.' idiomatically means:",opts:["It is hidden","It is obvious","It moves","It is visible"],a:1},{q:"In spoken French, 'ne' in negation is often:",opts:["stressed","doubled","dropped","moved to the end"],a:2},{q:"'de toute facon' means:",opts:["never","anyway","exactly","loudly"],a:1},{q:"Native rhythm relies partly on:",opts:["ignoring liaison","natural liaison and stress","avoiding verbs","only short words"],a:1}],
[{q:"'ch'est pas d'la tarte' is associated with which variety?",opts:["Quebec French","Belgian French","Ch'ti / Northern French","Standard French"],a:2},{q:"'Icitte' is a marker of:",opts:["Southern French","Standard French","Quebec French","Belgian French"],a:2},{q:"Neutral educated French is called:",opts:["Parisian slang","Verlan","Francais standard","Argot"],a:2},{q:"'septante' (70) is used in:",opts:["France","Belgium/Switzerland","Quebec","Algeria"],a:1},{q:"'char' for car is typical of:",opts:["France","Belgium","Quebec","Switzerland"],a:2}],
[{q:"A climax (gradation) in French rhetoric moves:",opts:["from strong to weak","from weak to strong","randomly","from abstract to concrete"],a:1},{q:"'repetition' as a rhetorical device creates:",opts:["confusion","irony","emphasis and rhythm","a question"],a:2},{q:"Parenthetical remarks are used to:",opts:["conclude","add asides or elaborations","change the topic","introduce a new argument"],a:1},{q:"A rhetorical question is meant to:",opts:["get a literal answer","guide the audience's thinking","fill time","end the talk"],a:1},{q:"A 'tricolon' groups elements in:",opts:["twos","threes","fours","fives"],a:1}],
[{q:"'synesthesie' mixes senses, for example:",opts:["une lumiere dure","une horloge rapide","un bleu silencieux","un grand mot"],a:2},{q:"'un souvenir fane' uses which device?",opts:["personnification","epithete transferee","metaphore","onomatopee"],a:1},{q:"In lyric poetry, an 'enjambement' is:",opts:["rhyme at line end","a run-on from one line to the next","a stanza break","a repeated refrain"],a:1},{q:"A 'metaphore' transfers meaning:",opts:["literally","figuratively between unlike things","only in poetry","by sound"],a:1},{q:"'personnification' gives human traits to:",opts:["people","non-human things","verbs","numbers"],a:1}],
[{q:"'le conseil juridique' is:",opts:["a judge","legal counsel / lawyer","a jury member","a notary"],a:1},{q:"'le produit interieur brut' is abbreviated as:",opts:["PIB","BRD","PNB","PCB"],a:0},{q:"In economics, 'la deflation' describes:",opts:["a currency revaluation","a general drop in prices","a general rise in prices","a trade deficit"],a:1},{q:"'l'hypothese' in research is:",opts:["a proven fact","a testable assumption","a footnote","a conclusion"],a:1},{q:"Specialized vocabulary should be used:",opts:["everywhere","precisely and in context","to confuse readers","never"],a:1}],
[{q:"Irony in French often signals with:",opts:["a literal statement with exaggerated tone","very direct criticism","formal register","a subordinate clause"],a:0},{q:"'C'etait vraiment brillant.' said after a failure uses:",opts:["hyperbole","understatement","verbal irony / sarcasm","a simile"],a:2},{q:"'Quelle coincidence!' used sarcastically expresses:",opts:["genuine surprise","sarcastic disbelief","a formal conclusion","a rhetorical question"],a:1},{q:"'litote' (understatement) is a form of:",opts:["hyperbole","irony","metaphor","alliteration"],a:1},{q:"Humour in language often depends on:",opts:["only grammar","shared context and timing","spelling","numbers"],a:1}],
[{q:"Efficient listening in a dense French lecture involves:",opts:["transcribing everything","focusing on keywords and structure","avoiding making notes","only listening without pausing"],a:1},{q:"'par voie de consequence' means:",opts:["in addition to this","by contrast","as a consequence / therefore","in a broader sense"],a:2},{q:"'Les resultats suggerent que...' means:",opts:["The results rule out that...","The results suggest that...","The results prove beyond doubt that...","The results are unrelated to..."],a:1},{q:"'une digression' in a lecture is:",opts:["the main point","an aside off the topic","the conclusion","a citation"],a:1},{q:"To follow a dense argument, identify the:",opts:["background noise","main thesis and supporting steps","speaker's clothes","room temperature"],a:1}],
[{q:"'l'etat des choses' means:",opts:["the opinion","the state of affairs / the facts","the proposal","the law"],a:1},{q:"'principe de subsidiarite' in political discourse means:",opts:["centralization","full autonomy","decision-making at the lowest appropriate level","judicial review"],a:2},{q:"A 'livre blanc' in policy is:",opts:["a blank document","an official government policy paper","a secret report","an informal memo"],a:1},{q:"'un projet de loi' is:",opts:["a passed law","a draft bill","a court ruling","a petition"],a:1},{q:"Policy argument requires:",opts:["emotion only","evidence and clear reasoning","slogans","no structure"],a:1}],
[{q:"'serendipite' in French is best:",opts:["translated word for word","used as a borrowed word for happy accidental discovery","replaced with 'bonheur'","avoided entirely"],a:1},{q:"'traduire' differs from 'interpreter' in:",opts:["language pair","written vs. spoken","formality","technical vocabulary"],a:1},{q:"A 'skopos' in translation theory defines:",opts:["the source text style","the target text purpose and audience","the translator's credentials","the payment structure"],a:1},{q:"'depaysement' is best rendered by:",opts:["a single English word","explanation or a borrowing","'fear'","'tired'"],a:1},{q:"A faithful translation preserves:",opts:["only the words","meaning, tone and intent","only the length","only the grammar"],a:1}],
[{q:"'Conserver le registre du texte' in editing means:",opts:["lowering the register","keeping the register and tone consistent","adding footnotes","translating for clarity"],a:1},{q:"In a masterclass critique, you address:",opts:["only weaknesses","only word choices","structure, argument, style, and language together","length only"],a:2},{q:"'metatextuel' refers to:",opts:["text about the content itself","text that is very long","text about other texts or writing processes","text with many footnotes"],a:2},{q:"A masterclass editor balances:",opts:["speed over quality","correction with the author's voice","only grammar","only style"],a:1},{q:"The final editing pass focuses on:",opts:["adding length","polishing consistency and nuance","changing the topic","removing all commas"],a:1}]
]
};
